<section>
	<article>
		<h2 class="dipay-3 text-center">Caracterizare de personaj</h2><hr>
		<p>Felix Sima este personajul principal din opera Enigma Otiliei scrisă de George Călinescu.  El este caracterizat direct şi indirect, fiind tipologia  personajului principal, rotund, dinamic, tipul intelectualului naiv. Caracterizarea directă este cea făcută de narator şi de alte personaje. Autocaracterizarea arata părerea personală a personajului despre sine. Caracterizarea indirectă analizează comportamentul, gesturile, faptele şi numele personajului.</p>

		<p>La început, Felix este caracterizat de către narator ca fiind “un tânăr de vreo optsprezece ani, îmbrăcat în uniformă de licean, arătând vârstă fragedă, dar începutul vieţii de adult. El este obosit din cauza greutăţii genţii pe care o ,,trecea des dintr-o mână în altă”, aducând cu el toată viaţa lui de până atunci într-o valiză. Faţa îi este descrisă ca fiind ,,juvenila şi prelungă aproape feminină din pricina şuviţelor mari de păr ce-i cădeau de sub şpaca". Astfel, trăsăturile feminine îi sunt înlăturare de ,,tăietură elinica a nasului”. Din chipul ,,dezorientat” se arata nesiguranţa pe sine a personajului care nu ştia încotro se îndreaptă viaţa lui.</p>
		 
		<p>Celelalte personaje îl caracterizează pe Felix în diferite ipostaze. Otilia îl considera mai mult un frate sau un copil, nu îl luă în serios deoarece ştia de ce este capabilă “zicea ea cu o comică maternitate”. Faţă de primirea ciudată a bătrânului, primirea sinceră a Otiliei îl impresionează pe Felix. Aglae îl priveşte cu austeritate, văzând în el încă un posibil pretendent la averea bătrânului. E încrezătoare în carieră pe care băiatul se străduieşte s-o facă, dar precizează că “medicina, cere ani mulţi”. În relaţia cu celelalte personaje, Felix apare ca un intelectual superior.</p>

		<p>Autocaracterizarea arata ambiţia personajului, optimismul şi buna părere a personajului despre propria persoană “să-mi fac o educaţie de om. Voi fi ambiţios, nu orgolios”.</p>

		<p>Comportamentul, gesturile, faptele conturează indirect o fire raţională, lucidă, cu o mare nevoie de certitudini, o fire analitică şi un spirit de observaţie foarte dezvoltat. De la început, Felix simte pentru Otilia o simpatie, care se transformă în iubire, fiind chinuit între a crede bârfele din clanul Tulea sau a păstra o dragoste pură pentru ea. Comportamentul Otiliei îl derutează şi nu-şi poate explica schimbările bruşte ale feţei. Plecarea ei cu Pascalopol la Paris îl dezamăgeşte, dar nu renunţa la cariera, eşecul maturizându-l.</p>
		
		<p>Felix Sima evoluează de la adolescenţă la maturitate, trăind experienta iubirii, dar şi ambiţia realizării pe plan profesional. Georgeta este un personaj care contribuie la maturizarea lui, arătându-i importanta în a nu renunţa la adevăratele lucruri care contează. El se comportă frumos şi respectuos chiar şi cu familia Tulea care încercau să îl tragă în jos. Chiar dacă devine gelos pe Pascalopol din cauza Otiliei îşi dă seama că interzicându-i să-l mai vadă relaţia se va distruge. El reuşeşte să-şi menţină viaţa profesională şi carieră pe primul loc, dând dovadă de personalitate şi perseverenţa având în vedere aceste caracteristici, personajul Felix Sima se încadrează în tipul intelectualului naiv, maturizându-se cu ajutorul celorlalte personaje.</p>
	</article>
</section>