<section>
	<article>
		<h2 class="dipay-3 text-center">Tema şi viziunea despre lume</h2><hr>
		<p>Introducere -> perioada interbelică -> în curând …</p>

		<p>G. Călinescu este o personalitate culturală românească de tip enciclopedic. El îşi desfăşoară activitatea la sfârşitul perioadei interbelice şi începutul celei contemporane, fiind deopotrivă critic şi istoric literar, biograf, monografist, eseist, romancier, poet şi dramaturg. Opera sa de căpătâi rămâne însă „Istoria literaturii romane de la origini până în prezent”, o lucrare amplă, de referinţă a culturii româneşti. Romanele călinesciene pornesc de la câteva puncte comune, teoretizate de criticul literar, ca manieră clasică de abordare a materialului epic. Astfel realismul de factură balzaciana se îmbină în mod original cu trăsăturile reprezentative moderniste, fiind evidente în scrierea sa, caractere mascate de o trăsătură dominantă, devenite tipologii de factură universală, adoptarea manierei balzaciene de redare a subiectului, evidenţă prin tehnica narativă, prin fixarea caracterelor în timp şi spaţiu, prin descrierea minuţioasă a cadrului, a arhitecturii clădirilor, a vestimentaţiei, dar şi pluri perspectivismul relativizarea perspectivei narative.</p>

		<p>Enigma Otiliei’ este un roman realist obiectiv de factură balzaciana care înglobează elemente de modernitate Încadrarea în proza realistă-obiectivă, este susţinută de prezentarea veridica a evenimentelor, perspectiva narativă obiectivă, utilizare persoanei a III-a, reliefarea individului ca produs al mediului din care face parte. Totodată personajele par a se încadra în tipologii (unele inspirate din prozele lui Balzac) reprezentative şi pentru epocă pe care o populează, dar elocvente şi pentru însuşiri general umane: Otilia Marculescu-cocheta, Felix Simandicosul, Leonida Pascalopol-moşierul, Costache Giurgiuveanu-avarul, Stanica Raţiu-parvenitul, Aglae-baba absolută fără cusur în rău, Aurica fata bătrânei, Titi-debilul mintal, Simion-senilul. Romanul apare în 1938 şi prezintă „în maniera realistă „viaţa burgheziei bucureştene de la începutul secolului al XX-lea dezvoltând tematici specifice acestei proze: de paternitate, moştenire şi ereditate, până la iubire/formare sentimentală şi moarte. Titlul iniţial a fost „Părinţii Otiliei", ilustrând ilustrând motivul paternităţii. Acesta a ulterior schimbat pentru a se accentua o trăsătură de caracter definitorie a eroinei. Personalitatea Otiliei este „enigmatică' fiind interpretată în mod diferit de fiecare dintre personajele romanului, ceea ce constituie o notă de modernitate a scrierii, anume realizarea perspectivei narative.</p>

		<p>Creaţia este amplă fiind alcătuită din douăzeci de capitole şi structurata în două planuri narative principale: istoria complicată a unei moşteniri şi destinul tânărului Felix Sima, orfanul care observă minuţios degradarea umană cauzată de dorinţa de acumulare materială. Secvenţele narative sunt construite pe baza înlănţuirii, naratorul respectând principiul cronologic al prezentării faptelor. Incipitul romanului fixează coordonatelevtemporale şi spaţiale „aflate în strânsă legătura „prezentând un mediu social nou pentru tânărul care în anul 1909, păşeşte pentru prima dată pa stradă Antim din Bucureşti "Într-o seară la începutul lui iulie 1909, cu puţin înainte de ora zece, un tânăr de vreo 18 ani, îmbrăcat în uniformă de licean, intra pe strada Antim. Finalul romanului este în strânsă relaţie cu incipitul cu care este simetric, trăsătura specifică scrierilor realist-obiective. După trecerea anilor Felix revine la locurile străbătute de licean pe strada Antim, care însă se schimbase şi ea, şi-şi aminteşte nostalgic de cuvintele cu care îl întâmpinase Costache,  "Aici nu stă nimeni”. Expoziţiunea este realizată prin fixarea acţiunii în timp şi spaţiu „în maniera balzaciană. Strada, dar şi casa lui moş Costache sunt descrise minuţios, prin prezentarea amănuntelor arhitecturale, aparţinând unor stiluri diferite. Casa bătrânului este veche, părăginita, decoraţiunile suntieftine, ; ceea ce sugerează unele trăsături ale proprietarului: incultura, zgârcenia, delăsarea. Familiarizarea lui Felix cu acest mediu se realizează prin procedeul restrângerii treptate a cadrului de la străzi, la case.la interioare, la fizionomie şi gesturile locuitorilor. 
		Felix este întâmpinat de într-un mod bizar de moş Costache, căci acesta pretinde că nu ştie cine este tânărul "Nu, nu, nu ştiu... nu nu stă nimeni aici”. Proprietarul imobilului din strada Antim este "un omuleţ subţire încovoiat, având capul "atins de o calviţie totală" şi "faţa aproape spână".Cu vocaţia unui mare romancier Călinescu adună aproape toate personajele romanului în salonul lui moş Costache, prilej pentru Felix de a le observa în detaliu.Se conturează astfel încă de la început conflict al romanului.</p>

		<p>Intriga scrierii este reprezentată, pe de-o parte de dorinţa obsesivă a clanului Tulea, condus de sora lui Giurgiuveanu, de a intra în posesia averii acestuia, iar pe de altă parte se axează pe prezentarea formării tânărului Felix Sima, care pătrunde într-un mediu social şi care marcat de întâlniră cu Otilia Marculescu, fiică vitregă a lui Costache.</p>

		<p>Planul moştenirii este prezentat minuţios de narator reliefând intrigile şi meschinăriile oamenilor apropiaţi bătrânului, dar care se lupta din răsputeri că, prin orice mijloc să dobândească averea acestuia. Bătrânul Costache „proprietar de imobile, acţiuni nu îndrăzneşte să o înfieze pe Otilia pentru că se teme de ura Aglaei, dar şi de cheltuială. Cu un instinct feroce de proprietate, Aglae consideră firească degradarea sentimentelor de familie. Unul dintre intruşii romanului „Stanica Raţiu, intra „în final, în posesia banilor lui Moş Costache, pe care îl ia de sub salteaua acestuia „provocându-i moartea. Stanica dovadă de ubicuitate şi susţine intriga romanului, până la rezolvarea în deznodământ: Stanica o părăseşte pe Olimpia, Aurica nu se căsătoreşte iar Otilia îl accepta drept soţ pe Pascalopol, în defavoarea lui Felix.</p>

		<p>Cel de-al doilea plan al romanului urmăreşte procesul de formare a tânărului Felix Sima, rămas orfan şi dat în grija tutorelui sau „Costache Giurgiuveanu. Evoluţia sa de la adolescenţă la maturitate „de la postura de licean la cea de medic este marcată de iubirea profund pentru Otilia Marculescu. Astfel se conturează un al doilea conflict al romanului, cel erotic, deoarece o perioadă îndelungată Felix este gelos pe Pascalopol, prietenul lui Costache „fiind convins că acesta este îndrăgostit de faţă.</p>

		<p>Un episod care reflectă specificul viziunii călinesciene este acela al galeriei personajelor. Încă de la început se profilează prin gesturi, replici, aluzii, tipare caracterologice: Naratorul notează minuţios fiecare aspect revelator: familiaritatea neobişnuită a gesturilor Otiliei, generează şi slăbiciunea lui Pascalopol pentru ea, răutatea acră a Aglaiei, refuzul speriat al lui Giurgiuveanu de a o împrumuta pe sora lui la cărţi, ocheadele Auricăi către Felix. Întregul tablou pare desprins dintr-o comedie.</p>

		<p>Un alt episod care subliniază tema moştenirii şi influenţa viziunii balzaciene se afla în capitolul XXVII.Moş Costache suferă un atac de congestie cerebrală şi este imobilizat la pat. Desfăşurarea este de asemenea, scenica. Ochiul naratorului urmăreşte cu atenţie gesturile avarului, preocupat de cheile sale plătind cu greu doctorul. Clanul Tulea sărbătoreşte moartea neîntâmplata, joacă partide de cărţi, se instalează milităreşte în casă şi veghează asupra moştenirii. Otilia şi Felix, singurii îndureraţi de starea bătrânului cheamă pe Pascalopol, care, loial, aduce un doctor universitar şi îngrijeşte pe bolnav.</p>

		<p>În opinia mea romanul 'Enigma Otiliei" reflecta imaginea societăţii burgheza din Bucureşti „transformărilor începutului secolului XX.Declinul unei lumi, pe rămăşiţele carea se clădeşte alta, cu energiile sale „este zugrăvit cu mijloacele clasice, împletit cu elemente de romantism şi modernism.</p>

		<p>În concluzie, romanul "Enigma Otiliei" se înscrie în sfera realismului critic, balzacian, dar, precum personajele sale „depăşeşte limitele unui tipar şi devine o individualitate".</p>
	</article>
</section>