<section>
	<article>
		<h2 class="dipay-3 text-center">Caracterizare personajului Ilie Moromete</h2><hr>
		<p> Operă literară “Moromeţii” a fost scrisă de Marin Preda şi publicată în perioada postbelică a literaturii române în două volume, primul volum în anul 1955, iar al doilea în anul 1967. Opera este bazată pe viaţă scriitorului.</p>

		<p> “Moromeţii” aparţine genului epic şi este un roman social obiectiv postbelic. Amplă frescă a satului românesc surprinde numeroase personaje reprezentative pentru diferite categorii sociale, tipuri umane sau teme înfăţişate şi impune o tipologie nouă. Personajul “Ilie Moromete” este personajul principal al primului volum şi secundar celui de-al doilea. Volumul I îl conturează pe Ilie Moromete în mod complex, cap de familie, dominând copiii din prima şi a doua căsnicie cu autoritate, cu o poziţie centrală în lumea satului, fiindcă era cel mai inteligent şi abil dintre ţărani. Spre deosebire de alte personaje, îşi ascundea gesturile prin puterea disimulării.</p>

		<p> Volumul al II-lea îl găseşte pe Ilie Moromete că personaj secundar şi un om dominat de timpul schimbărilor. Îşi pierde cele două valori, familia şi pământul, ca urmare moartea personajului reprezintă o stingere a lumii satului arhaic.El este caracterizat direct de către narator şi alte personaje sau autocaracterizare ori indirect prin limbaj, gesturi, fapte, atitudini faţă de alte personaje sau prin nume. Caracterizarea directă făcută de narator arată că Ilie Moromete “era cu zece ani mai mare decât Catrina” şi acum avea acea vârstă între tinereţe şi bătrâneţe când numai nenorociri sau bucurii mari mai pot schimba firea cuiva. Chiar la începutul romanului, în scena cinei “Moromete stătea parcă deasupra tuturor”. În alt loc, naratorul spune că “Moromete avea uneori obiceiul (semn de bătrâneţe sau poate nevoia de a se convinge că şi cele mai întortocheate gânduri pot căpăta glas) de a se retrage pe undeva prin grădină şi de a vorbi singur ". Caracterizarea directă făcută de alte personaje sugerează percepţia diferită asupra personajului. Soţia sa, Catrina îi reproşează lenea şi plăcerea vorbei “Toată ziua stai la drum şi bei tutun”, sora sa Guica îi poartă pică deoarece căsătorindu-se, ea a fost obligată să se mute din casă, rămânând singură, în timp ce Cocoşila, prietenul său îi zice mereu “Eşti prost!”, calificativ ce ascunde, însă pe de o parte simpatia, iar pe de altă parte invidia faţă de inteligentă şi spontaneitatea personajului. Procedeul autocaracterizării rămâne definitoriu prin mărturisirea făcută de Moromete doctorului, cu o sublimă trufie a omului ce şi-a respectat condiţia şi menirea: “Domnule, eu întotdeauna am dus o viaţă independentă!”.</p>

		<p> Caracterizarea indirectă prin limbaj arata schimbările majore şi dramatice prin care trece personajul: la început are plăcerea de a povesti cu lumea, răspunzând în multe cuvinte la salutul oamenilor, ulterior este poreclit “Mutul”, “nu se mai putea vorbi cu el, spuneai una şi el ascultă şi ai fi zis că înţelegea, ca să te pomeneşti pe urmă că răspunsurile pe care le dădea veneau din altă parte”. El este un disimulant, care vorbeşte singur, fiindcă nu considera că merită cineva să-i asculte gândurile. Disimularea este o reacţie defensivă, ulterior devine o a doua natură a personajului, arătând înstrăinarea tragică “Lui Moromete parcă îi zburase mintea din cap şi cu bună ştiinţă făcuse schimb cu a altui ţăran care vorbea cu tine aşa cum vorbeşti cu un cal sau cu o vacă”. În gura lui, cuvântul capăta fascinaţie magică, cele mai obişnuite întâmplări devin aventuri. Nedumerirea prefăcută a lui Ilie, pauzele în rostire, interjecţiile şi lăcomia cu care vrea să afle detaliile picante în situaţia despre cei care îşi “amendează copiii”, vânzându-le pământul.

		<p> Caracterizarea indirectă prin gânduri, idei arată că este îndrăgostit de viaţă, o vede că pe un spectacol, o contemplă, crede că timpul e răbdător, iar când vede că s-a înşelat tot nu se teme de trecerea sa “Moromete nu găsea în el nicio frică faţă de trecerea anilor”.</p>

		<p> Caracterizarea indirectă prin atitudini faţă de oameni sugerează că îşi iubeşte copiii, dar e mai bine să-i ţină din scurt. Încearcă să-şi îndrepte greşelile făcute faţă de ei, recunoaşte că marea lui greşeală a fost că nu l-a lăsat să facă mai departe şcoala pe Niculae, fiul său cel mic. Nu înţelegea lumea fiilor cei mari, dar e convins că se vor schimba mai târziu. El se simte mândru şi dispreţuitor faţă de Bălosul pe care îl înjura întotdeauna (în gând) pentru dorinţa de îmbogăţire, iar acesta simţind superioritatea vecinului său, nu-şi doreşte decât să-l vadă umilit. Se simte superior şi nu-şi poate stăpâni pornirea de a fi ironic cu ce care nu-l înţeleg. Atitudinea de şef absolut al familiei este subliniată în timpul cinei.</p>

		<p> Caracterizarea indirectă prin gesturi sau chiar mersul său trădează stările sale de meditaţie “Îşi lasă fruntea în pământ şi mersul i se încetini. Era mersul lui când se gândea şi când nu mai vedea nimic în jur.” Supărarea, liniştea, nedumerirea, veselia forţată, neputinţa" sunt prezente în comportamentul omului. Subliniate de gesturi şi de o mimică expresivă. La fel de elocventă este scena prânzului la câmp, deşi se frige cu fasolea fierbinte, nu se exteriorizează în niciun fel, aşteptând curios şi amuzat ca Paraschiv, fiul său, să păţească acelaşi lucru, lăsându-l să se frigă, demonstrând astfel lăcomia, apoi prevenitor îi oferă apă rece şi se interesează grijuliu dacă s-a fript rău, Na, Paraschive, bea apă, se precipită Moromete, apucând bota în braţe şi intinzandui-o grijului. Te-ai ars rău? Eu credeam că e rece, mărturisind el naiv". Caracterizarea indirectă prin idealuri şi valori arată că personajul are o concepţie de viaţă aparte, centrată pe ideea libertăţii spirituale şi consideră că omul este dator să ţină la rostul şi menirea lui, chiar dacă este bun sau rău. Personajul este considerat “cel din urmă ţăran adevărat”. Caracterizarea indirectă prin fapte a personajului spune că el continuă să fie preocupat de politica şi după ce se instalează comuniştii la putere. Fiind inteligent, prevede marile schimbări dramatice şi le împărtăşeşte prietenilor săi. </p>

		<p> El prinde viaţă (că personaj principal) nu doar din faptele pe care le face cât şi din comportamentul său. Faptele săvârşite de Moromete sunt cele ale unui ţăran obişnuit cu familie şi griji. El merge la câmp, dar nu se omoară cu munca, vorbeşte cu vecinii, îl vizitează pe altul şi îşi bate copiii când aceştia întrec măsura. Important pentru acest ţăran nu este ceea ce face, cu cum face sau cum le prezintă întâmplările celor care-l ascultă. Ceea ce face, în mare parte, se modifică în funcţie de ceea ce simte, de starea lui, de aceea devine o nedumerire pentru cei din jurul său. Niciuna din faptele sale nu dovedeşte grabă, căci timpul are răbdare cu oamenii. El îi interzice fiului său cel mic, Niculae, să mai meargă la şcoală, considerând că nu-i aduce niciun “beneficiu”, iar acesta se înstrăinează de familie. În al doilea volum, cei doi rămân certaţi, Moromete moare, iar Niculae visează că s-au împăcat.</p>

		<p> Având în vedere aceste caracteristici, caracterizarea lui Ilie Moromete demonstrează că personajul are o complexitate care îl aseamănă cu un intelectual veritabil, fiind considerat un ţăran filosof.</p>
	</article>
</section>