<section>
	<article>
		<h2 class="dipay-3 text-center">Relaţia între două personaje din romanul ,,Moromeţii”</h2><hr>
		<p>Romanul de după al Doilea Război Mondial este mascat de caracterul social-politic. Primii ani ai, obsedatului deceniu” proletcultist înregistrează producţii ilizibile astăzi, compromise, respectând temele şi convenţiile epice ale momentului, pe linia dogmatică realist-socialistă, sub presiunea unei cenzuri totalitare. Capodoperă a literaturii romane, „Moromeţii” marchează, prin umanitatea evocată, unul din momentele de vârf ale prozei, Marin Preda fiind un continuator al romanului românesc de inspiraţie rurală (pe linia inaugurată de Slavici, Sadoveanu, Rebreanu), dar cu o viziune modernă asupra acestei tematici.</p>

		<p>Roman postbelic, realist, obiectiv, şi tradiţional, cu numeroase elemente de modernitate, „Moromeţii” este alcătuit din două volume, primul apărut în 1955, iar al doilea în 1967. Amplă creaţie, înglobează elemente specifice romanului realist, obiectiv şi tradiţional: naraţiunea la persoana a III-a, refacerea culorii locale, veridicitate, menţinerea unităţii de timp şi spaţiu în raport cu acţiunea, îmbinate însă cu cele moderne: dilatarea timpului în partea I a romanului pentru a crea impresia de „timp răbdător”, tehnica de construcţie a personajului prin motivul măştii, ridicarea faptului banal la motivul simbolului. De asemenea, trebuie remarcat faptul că obiectivitatea şi omniscienţa naratorului sunt diminuate de prezenţa unor personaje reflector, elemente de modernitate ale romanului (Ilie Moromete, în primul volum şi Niculae, fiul său, în volumul al doilea), dar şi de prezenţa unor personaje-narator care aduc lămuriri suplimentare despre ceea ce se petrece dincolo de prim-planul acţiunii.</p>

		<p>Relaţia dintre realitate şi ficţiune este una foarte strânsă, reprezentată fiind de crearea eroului central după modelul tatălui scriitorului, cât şi de redarea satului natal, Siliştea-Gumeşti, din judeţul Teleorman, ca spaţiu al desfăşurării acţiunii.</p>

		<p>Tema centrală a romanului este destrămarea familiei şi a civilizaţiei tradiţionale ţărăneşti, mai exact dispariţia din istorie a clasei ţăranilor proprietari de pământ, asociate însă cu cea a timpului neiertător.</p>

		<p>Viziunea despre lume se conturează prin meditaţiile autorului asupra intervenţiei brutale asupra istoriei în satul tradiţional, considerat până atunci un univers în afară timpului, intervenţie care ne duce la transformarea şi chiar dispariţia unor instituţii rurale, a unor mentalităţi şi chiar a unor filosofii de viaţă.</p>

		<p>Titlul romanului aşază în centru tema familiei. Format dintr-un substantiv propriu la numărul plural, acesta îndreaptă atenţia cititorului către toţi membrii familiei, cu toate conflictele lor, dar şi către întreaga colectivitate ţărănească; familia Moromete, fiind reprezentativă pentru întreaga colectivitate de dinaintea şi de după cel de-al Doilea Război Mondial.
		Ilie Moromete, personajul principal al romanului, reprezintă un tip aparte de ţăran în literatura noastră. Nu este o fiinţă rudimentară, ci are o complexitate psihologică ce trădează inteligenta, ironie sau chiar spirit contemplativ. Este un personaj exponenţial, reprezentând concepţia tradiţională fata de pământ şi de familie, al cărui destin exprima moartea unei lumi, cea a satului tradiţional. Moromete este un patern familiar, autoritatea principală în familia sa, pe care încearcă să o întreţină cu ajutorul cultivării pământului.</p>

		<p>Niculae este fiul din cea de-a doua căsătorie a lui Moromete, cea cu Catrina, fiind mezinul familiei. Sarcina principală a lui Niculae este să aibă grijă de oaia neastâmpărată Bisisica, principala lui sursă de suferinţă, prin care Preda distruge mitul mioritic, aşa cum, prin Niculae, distruge şi mitul copilăriei vesele şi lipsite de griji. Scena cinei din prima parte a volumului | este revelatoare pentru statutul mezinului în cadrul familiei, implicit în ochii tatălui — acesta era aşezat în dreptul mamei sale, stând pe jos, pentru că nu avea scaun.</p>

		<p>Mezinul nu era, aşadar, un membru important al familiei, fapt dovedit şi de conflictul pe care îl va avea cu tatăl său în ceea ce priveşte dorinţa lui de a se duce la şcoală. Copilul îşi doreşte cu ardoare să meargă la şcoală şi, în ciuda acordului mamei sale, nu primeşte sprijin din partea lui Ilie, care trebuie să îi plătească taxele. Acesta susţine că învăţătura nu îi aduce niciun beneficiu şi îl ironizează: "altă treaba n-avem noi acuma! Ne apucăm să studiem”.</p>

		<p>Relaţia afectivă dintre cei doi este şubrezită de lipsa acută de comunicare. Moromete are impresia că cei din jur îl înţeleg şi că gesturile sale nu necesită nicio justificare, nicio explicaţie faţă de aceştia. Este un tată autoritar, care nu acceptă să fie contrazis în vreun fel. Moromete îşi iubeşte însă copiii. Ironia faţă de fiii săi se prezintă sub forma unor observaţii cu scop corectiv şi nu izvorâte din dispreţ sau răutate. De exemplu, lui Niculae, care întârzia să vină la masă, îi spune la un moment dat: „Te duseşi în grădină să te odihneşti, ca până acum stătuşi!” Totuşi, când vine vorba de manifestarea afecţiunii, acesta îşi cenzurează orice gest.</p>

		<p>La serbarea de sfârşit de an şcolar, la care Niculae ia premiul I, Moromete vine pregătit să audă că fiul său rămăsese repetent. Scena denotă atât lipsa de interes a tatălui pentru preocupările fiului său, pentru viaţa acestuia din afara gospodăriei, cât şi lipsa de încredere în capacităţile intelectuale ale băiatului. Stinghereala copilului, criza de friguri care îl cuprinde în timp ce încerca să recite o poezie îl impresionează pe Moromete, dar gesturile sale de mângâiere sunt schiţate cu multă stângăcie. Dorinţa sa de a-i menţine poziţia de autoritate în familie printr-un comportament dur, uneori chiar aspru, a dus tocmai la slăbirea relaţiilor dintre membrii acesteia, dovadă fiind şi fuga de acasă a fiilor celor mari cu oile şi caii la Bucureşti.</p>

		<p>În volumul al doilea, ce prezintă o perioadă de un sfert de veac, conflictul dintre Moromete şi Niculae trece în prim-plan, pentru că tatăl şi fiul reprezintă mentalităţi diferite: În Moromeţii, interesantă e problema lui Niculae, căci conflictul dintre el şi Moromete simbolizează conflictul dintre două concepţii despre ţăran. Tocmai din această cauză, ei devin reflectori: motivaţiile lor lăuntrice interesează nu numai ca expresie a adaptării sau dezadaptării spontane de o lume, ci Şi ca filosofie de existenţă. (Nicolae Manolescu) Moromete îşi va concentra toată energia pentru a-i aduce acasă pe fiii săi cei mari şi îl va retrage pe Niculae de la şcoală pe motiv că nu îi aduce „niciun beneficiu”. Atunci se va produce o ruptură între tată şi fiu. Îşi va pierde nu doar autoritatea parentală, ci şi pe cea în sat, fapt care îl face să scadă şi mai mult în ochii lui Niculae, care remarcă: „îl vezi cum îi ia altul vorbă din gură, fără niciun respect şi el lasă fruntea în jos şi nu zice nimic”. Acum un antimoromeţian ca filosofie a existenţei, Niculae Moromete va ajunge activist de partid, adeptul unei „noi religii a binelui şi a răului”.</p>

		<p>Disensiunile între tată şi fiu capătă acum sensul unor maniere diferite de a concepe existenţa; Ilie Moromete reprezintă concepţia tradiţională faţă de pământ şi de familie, în timp ce Niculae, „apostol al marilor transformări”, este exponentul unei noi viziuni asupra satului, cea a socialismului.</p>

		<p>Zece ani mai târziu, destituit din funcţia pe care i-o oferise comunismul, Niculae îşi continuă studiile, devine inginer horticultor şi se căsătoreşte cu o fată din sat. Moromete îşi va trăi ultimii ani din viaţă tot mai departe de tot ce se întâmpla, tot mai rupt de lume. Marea înfrângere a lui Ilie Moromete este însingurarea, dar mai ales înstrăinarea de sine însuşi, criza sa atingând dimensiuni tragice. La înmormântarea tatălui său, Niculae află de la sora sa, Ilinca, de faptul că Moromete se stinsese încet, fără de a suferi de vreo boală.</p>

		<p>Tânărul are remuşcări pentru că îşi părăsise tatăl în ultimii ani şi nu are linişte până când imaginea acestuia nu îi apare în vis, „în lumina veşnicei zile de vară care scălda bătătura şi salcâmii de acasă”.</p>

		<p>Conflictul dintre cei doi va fi soluţionat, se vor împăca în visul lui Niculae. În acest deznodământ tragic, se stabileşte un echilibru care lipsise de la bun început relaţiei dintre cele două personaje; mezinul reuşeşte în final să îşi înţeleagă tatăl şi îşi dă seama de afecţiunea pe care i-o poartă. Relaţia dintre Moromete şi fiul său, Niculae, este una marcată de tragism, căci comunicarea deficitară a dus la o ruptură nefirească între cei doi. Însa ceea ce oferă şi mai mult dramatism situaţiei este tocmai regretul fiului din finalul romanului, remuşcările pe care le are Niculae pentru faptul că îşi părăsise părintele.</p>

		<p>Fiul îşi dă seama prea târziu de greşelile sale. Un consens la care ar fi trebuit să se ajungă mai devreme a fost stabilit numai după moartea lui Moromete. Trufia lui Moromete, incapacitatea celor doi de a comunica unul cu celălalt, diferenţa dintre concepţiile lor asupra vieţii, precum şi refuzul fiecăruia de a ajunge la un compromis au dus la un deznodământ tragic, care ar fi putut fi evitat.</p>
	</article>
</section>