<section>
	<article>
		<h2 class="dipay-3 text-center">Temă şi viziunea despre lume în romanul ,,Moromeţii”</h2><hr>
		<p>Romanul de după al Doilea Război Mondial este mascat de caracterul social-politic. Primii ani ai, obsedatului deceniu” proletcultist înregistrează producţii ilizibile astăzi, compromise, respectând temele şi convenţiile epice ale momentului, pe linia dogmatică realist-socialistă, sub presiunea unei cenzuri totalitare. Capodoperă a literaturii romane, „Moromeţii” marchează, prin umanitatea evocată, unul din momentele de vârf ale prozei, Marin Preda fiind un continuator al romanului românesc de inspiraţie rurală (pe linia inaugurată de Slavici, Sadoveanu, Rebreanu), dar cu o viziune modernă asupra acestei tematici.</p>

		<p>Roman postbelic, realist, obiectiv, şi tradiţional, cu numeroase elemente de modernitate, „Moromeţii” este alcătuit din două volume, primul apărut în 1955, iar al doilea în 1967. Amplă creaţie, înglobează elemente specifice romanului realist, obiectiv şi tradiţional: naraţiunea la persoana a III-a, refacerea culorii locale, veridicitate, menţinerea unităţii de timp şi spaţiu în raport cu acţiunea, îmbinate însă cu cele moderne: dilatarea timpului în partea I a romanului pentru a crea impresia de „timp răbdător”, tehnica de construcţie a personajului prin motivul măştii, ridicarea faptului banal la motivul simbolului. De asemenea, trebuie remarcat faptul că obiectivitatea şi omniscienţa naratorului sunt diminuate de prezenţa unor personaje reflector, elemente de modernitate ale romanului (Ilie Moromete, în primul volum şi Niculae, fiul său, în volumul al doilea), dar şi de prezenţa unor personaje-narator care aduc lămuriri suplimentare despre ceea ce se petrece dincolo de prim-planul acţiunii.</p>

		<p>Relaţia dintre realitate şi ficţiune este una foarte strânsă, reprezentată fiind de crearea eroului central după modelul tatălui scriitorului, cât şi de redarea satului natal, Siliştea-Gumeşti, din judeţul Teleorman, ca spaţiu al desfăşurării acţiunii.</p>

		<p>Tema centrală a romanului este destrămarea familiei şi a civilizaţiei tradiţionale ţărăneşti, mai exact dispariţia din istorie a clasei ţăranilor proprietari de pământ, asociate însă cu cea a timpului neiertător.</p>

		<p>Viziunea despre lume se conturează prin meditaţiile autorului asupra intervenţiei brutale asupra istoriei în satul tradiţional, considerat până atunci un univers în afară timpului, intervenţie care ne duce la transformarea şi chiar dispariţia unor instituţii rurale, a unor mentalităţi şi chiar a unor filosofii de viaţă.</p>

		<p>Titlul romanului aşază în centru tema familiei. Format dintr-un substantiv propriu la numărul plural, acesta îndreaptă atenţia cititorului către toţi membrii familiei, cu toate conflictele lor, dar şi către întreaga colectivitate ţărănească; familia Moromete, fiind reprezentativă pentru întreaga colectivitate de dinaintea şi de după cel de-al Doilea Război Mondial.</p>

		<p>Primul volum se caracterizează prin folosirea tehnicii decupajului şi se observă accelerarea treptată, gradată a timpului naraţiunii. Acest volum este structurat în trei părţi şi are o acţiune concentrată, desfăşurată pe parcursul unei singure veri, cu trei ani înainte de izbucnirea celui de-al Doilea Război Mondial. Prima parte, derulată lent, se desfăşoară de sâmbătă seara, când Moromeţii se întorc de la câmp, până duminică noaptea, când Polina, fiica lui Tudor Balosu, fuge de acasă cu Birica, un flăcău sărac. A doua parte, narata din ce în ce mai lent, în concordanţă cu un timp care „nu mai avea răbdare”, cuprinde evenimentele din două săptămâni, de la plecarea lui Achim cu oile de la Bucureşti până la serbarea şcolară la care Niculae, mezinul familiei, obţine premiul I. Cea de-a treia parte, şi mai extinsă ca durată începe cu scena secerişului şi se termină cu fuga lui Paraschiv şi a lui Nilă la Bucureşti, dând o grea lovitură familiei, la sfârşitul verii.</p>

		<p>Compoziţional, primul volum este realizat printr-o relaţie simetrică incipit-final, simetria fiind dată de cele două enunţuri care încadrează volumul şi care aduc în discuţie tema timpului.</p>

		<p>Incipitul romanului conţine atât repere temporale cât şi o referire la cele două ipostaze a timpului: „În Câmpia Dunării, cu câţiva ani înaintea celui de-al Doilea Război Mondial, se pare că timpul avea cu oamenii nesfârşită răbdare.”. Se evidenţiază astfel un timp subiectiv, iluzoriu care este numai aparent răbdător „se pare că”, benefic şi tolerant, iar pe de altă parte un timp obiectiv, real, care este ameninţător, agresiv şi necruţător aflat în dezacord cu primul. Finalul surprinde aceeaşi temă a timpului, fiind însă ipostaza obiectivă, reală: „Trei ani mai târziu, izbucnirea celui de-al Doilea Război Mondial. Timpul nu mai avea răbdare. Devenit rău şi duşmănos, timpul schimba acum viaţa lui Ilie Moromete şi determină apusul unei lumi — satul tradiţional.</p>

		<p>Primul plan al romanului urmăreşte destrămarea familiei Moromeţilor, o familie numeroasă, măcinată de nemulţumiri mocnite. Ilie Moromete, ţăran din clasa de mijloc, încearcă să păstreze întreg pământul familiei sale, pentru a-l lăsa apoi băieţilor. Paraschiv, Nilă şi Achim, băieţii cei mari, îşi doresc însă independenţa economică simţindu-se nedreptăţiţi deoarece, după moartea mamei lor, Ilie s-a însurat cu Catrina, cu care are încă trei copii: Ţâţa, Ilinca şi Niculae. Îndemnaţi de sora lui Ilie, Maria Moromete, poreclită Guica, cei trei băieţi pun la cale să fugă până la Bucureşti cu oile cumpărate de Moromete printr-un împrumut la bancă, dar vor să ia şi caii, indispensabili pentru munca la câmp. Achim pleacă primul, urmând să vină şi ceilalţi doi. Aflând de planurile lor, Moromete încearcă să împiedice destrămarea familiei dar Paraschiv şi Nilă vor fugi şi ei, luând caii, banii şi lucruri din ladă de zestre a fetelor. Moromete este nevoit să vând o parte din pământ pentru a cumpăra alţi cai şi a plăti fonciera, rată la bancă, datoriile şi taxele pentru şcoala lui Niculae.</p>

		<p>Al doilea plan înfăţişează destinul comunităţii rurale: boala lui Botoghina, revolta taranului Tugular, dragostea dintre Polina şi Birică. Astfel se completează acţiunea romanului conferindu-i caracterul monografic sau fresca socială. Prin tehnica decupajului, Marin Preda extrage scene din viaţa satului, având multiple semnificaţii simbolice. De duminică, în sunet de clopot şi de rugi şi invocaţii înălţate din cimitir, este de o măreţie tragică, prevestind declinul unei lumi încremenite în rânduielile vechi.</p>

		<p>În opinia mea, operă literară „Moromeţii” este un roman realist-obiectiv, oferind o imagine amplă asupra percepţiei scriitorului despre lumea rurală înainte şi după cel de-al Doilea Război Mondial.</p>

		<p>În concluzie, tema fundamentală a operei este aceea a relaţiei dintre personaj şi istorie „Moromeţii” este un demers literar ce evocă soarta lumii ţărăneşti în confruntarea brutală cu istoria.</p>
	</article>
</section>