<section>
	<article>
		<h2 class="dipay-3 text-center">Leoaica tânără, iubirea</h2><hr>
		<p>Neomodernismul este un curent literar manifestat după 1960 din dorinţa eliberării poeziei de sub dogmele întunecatului deceniu (realismul specialist). Poezia neomodernistă se caracterizează prin particularităţi precum: eliberarea de sub dogmele proletcultiste, recuperarea valorilor modernismului interbelic, redefinirea poeticului, abordarea marilor teme ale liricii, ambiguitatea limbajului. La Nichita Stănescu poezia reiese din dorinţa de a reda frumosul într-o manieră accesibilă omului. El este creatorul uni poezii profunde caracterizată prin dramaticul gândirii lui Blaga sau lui Eminescu.</p>

		<p>Titlul este exprimat printr-o metaforă în jurul căreia se constituie cele 3 strofe. Metafora sugerează iubirea frumoasă, puternică, tânără şi extazul poetic la apariţia neaşteptată a iubirii.</p>

		<p>Compoziţional, poezia este formată din trei strofe încadrate în neo modernism prin absenţa prozodiei tradiţionale şi prin ritmul interior al sentimentelor şi ideilor poetice. Prima strofă exprima vizualizarea sentimentelor de iubire, sub forma unei tinere leoaice agresive, care sare “în fata” eului liric, având efecte devoratoare asupra identităţii sinelui, înfingându-şi “colţii albi” şi muşcându-l “de faţă”. Pronumele la persoana I, “mi", “mă” potenţează confesiunea eului poetic în sensul că el era conştient de eventualitatea ivirii sentimentului de dragoste. Personificarea iubirii crează sugestia începutului tulburător al dragostei adolescentine, care sperie prin spontaneitatea ei, Aventura iubirii depinzând de voia celui atacat.</p>

		<p>Dacă în prima secvenţă dragostea este văzută din exterior. Cea de-a doua secvenţă prezentată-n următoarea strofă, dezvăluie iubirea văzută din interior şi accentuează efectul psihologic al neaşteptatei întâlniri. De data aceasta individual trece într-o altă dimensiune a existenţei, iubirea poziţionându-l în centrul Universului. Forţa agresivă a iubirii pare să reordoneze lumea după propriile legi, într-un joc al cercurilor concentrice că simbol al perfecţiunii, eul liric simţindu-se în acest nou univers un adevărat “Axis Mundi”. Strofa a treia revine la momentul iniţial “leoaica arămie/cu mişcări viclene” fiind metafora iubirii agresive, insinuate, devoratoare pentru eul liric. Eul liric se simte confuz şi bulversat de un sentiment extrem de puternic, acesta identifica sentimental, nu mai este o “leoaică tânără” oarecare, ci “arămie”. Ştie că iubirea este perfidă, dar fericirea vine acum după o perioadă ternă a vieţii. Iubirea, ca formă a spiritului, învinge timpul dând energie şi profunzime vieţii.</p>

		<p>Poezia este o romanţă cantabilă a iubirii sentiment materializat, vizualizat de Nichita Stănescu, stare sufletească că capăta puteri demiurgice asupra sensibilităţii eului poetic.</p>
	</article>
</section>