<section>
	<article>
		<h2 class="dipay-3 text-center">Caracterizarea personajului Vitoria Lipan</h2><hr>
		<p>Vitoria este personajul principal, o femeie voluptoasă, curajoasă, inteligentă și lucidă care apare în toate scenele romanului și prin intermediul căreia se realizează acțiunea, dar se configurează și alte portrete. S-a consacrat în conștiința publicului cititor formula "romanul unui suflet de munteancă", prin care se certifică un mare adevăr - nu subiectul conferă spectaculozitate operei ci eroina prin modul ei specific de a se raporta la existență.</p>
		<p>Personajul Vitoria Lipan este descries în text în trei ipostaze și anume: cea de soție de oier, cea de mamă cu trei copii, și cea de detectiv. Vitoria Lipan cucerești și prin frumusețea și farmecul ei fizic căci "la cei patruzeci de ani ai săi, ochii ei căprui răsfrângeau lumina castanie a părului „însă privirea ei era dusă departe, semn al gândurilor în care era adâncită și o copleșeau".</p>
		<p>Femeia nu mai era tânără, "dar avea o frumsețe neobișnuită în privire". Înfățișarea fizica ilustrează îngrijorarea femeii pentru lipsa bărbatului ei și figurează zbuciumul sufletesc ce o vor stăpânii și o vor macină, până ce îi vă descoperii și pedepsii pe ucigașîi lui Nechifor Lipan.</p>
		<p>Femeie aspră, Vitoria este o soție harnică și pricepută care duce grijile unei gospodării mari.Astfel, ea știe ce produse mai are de vânzare, se tocmește cu iscusință de negustor cu cei care vin să cumpere sau merge ea însuși la câmpie, unde vinde produsele.</p>
		<p>Organizată, meticuloasă, cu un deosebit simț practic înainte de plecare în cautrea lui Lipan, ea orânduiește totul cu abilitate și exactitate încât… Întreprinzătoare și prevăzătoare, vinde produsele dar duce peste noapte banii la preot pentru a nu fii prădată. Conștien</p>ta de pericolele care-i pândesc pe drum, îi face lui Gheorghiță un baltag pe care preotul îl sfințește, iar pentru sine ia o pușcă pe care s-o folosească în caz de nevoie.
		<p>Vitoria este o femie credincioasă și respectă obiceiurile strămoșești. Înainte de a pleca, se consultă cu preotul „merge la mănăstire unde se roagă la icoana Sfintei Ana, ține post douăsprezece vineri, se spovedește și se împărtășește sau face daruri bisericii. În drumul ei întâlnește un botez și o nuntă și de fiecare dată respectă tradiția așa cum îndeplinește toate cele creștinești pentru înmormântarea și pomenirea lui Nechifor Lipan.</p>
		<p>Totodată „femeia este superstițioasă, căci ea crede în vise și în semene, în descântece și în vrăji și de aceea nu uită să meargă la baba Maranda, vrăjitoarea, pentru a afla despre soțul ei. Visul în care Lipan apare cu spatele întors peste o apă neagră și cântecul cocoșului slobozit o singură dată cu piscul întors către poartă, o macină și-i dau certitudinea că bărbatul ei nu se mai întoarce „deoarece a fost ucis ".</p>
		<p>Eroina impresionează și prin luciditate și stăpânire de sine, căci, inițial hotăraște să-l trimiaă doar pe Gheorghiță în căutarea lui Nechifor dar, „își da seama că acesta nu are mintea și experiență ei de viață și pleacă împreună. Este înzestrată cu inteligența pe care și-o manifestă într-o diversitate de împrejurări. Reușește să-l convingă pe Gheorghiță de necesitatea plecării la drum, aducandu-i argumentele cele mai puternice culminând cu acelea că "jucăriile au stat. De-acu trebuie să te arați bărbat. Eu n-am alt sprijin și am nevoie de brațul tău ".</p>
		<p>De asemena „culege cu abilitate informațîi de la cei din jur „dovedind o mare pricepere în descifrarea sufletului oamenilor, în slujba căruia pune felul sau de a vorbii cu aceștia. Uneori cuvintele sale sunt veritabile maxime "Cine nu cearcă, nu chibzuiește" alteori vorbele sale evidențiază un umor și o ironie subtila. În relația cu copii se dovedește tolerantă cu Gheorghiță pentru că se vede sfios și nesigur.</p>
		<p>Ea îl apară și îl ocrotește de câte ori în ochii lui Lipan erau "nouri de vreme rea" iar atunci când își dă seama că a rămas singurul sprijin al gospodăriei sale face din acesta un bărbat curajos și energic. Cu Minodora este mai neîndurătoare pentru că vrea să o educe în spiritual tradiției „pornind de la îmbrăcăminte „preocupări și comportament moral și urmărind să o căsătorească cu un gospodar cu casă și avere. Împovărată de griji și de neliniști, pe lângă manifestele ei exterioare, Vitoria trăiește un zbucium interior devastator.</p>
		<p>Ea găsește însă tăria morală de a se rupe din gânduri și din singurătate și de apleca în căutarea soțului. Ceea ce îi dă putere să ia această hotărâre este dragostea pe care i-a purtat-o soțului sau.</p>
		<p>Acțiunile eroinei relevă un caracter complex în care defectele nu anulează calitățile „ci le impune în realizarea scopului și a responsabilitățîi pe care personajele și le asumă.</p>
		<p>De remarcat este diversitatea procedeelor de caracterizare folosite de scriitor: direct „prin descriere, prin părerea celorlalte personaje sau indirect, prin fapte, plrin atitudine, prin relația cu celelalte personaje sau prin felul de a vorbi. În opinia mea, cu toate greutățile hotărâre este dragostea pe care i-a purtat-o soțului său. În opinia mea, cu toate greutățile întâmpinate în drumul său și investigatille făcute, Vitoria dovedește tenacitate, dârzenie și voință de neînfrânt deoarece nu renunță „indeplinindu-și dorința de a-l găsii pe Nechifor Lipan și de a-l pedepsi pe ucigaș.</p>
		<p>Astfel spiritul ei justițiar învinge și „odată scopul atins „Vitoria vă revenii la vechile îndeletniciri și preocupări, căci viață își urmează cursul spiritual. În concluzie, exponent a unui stavechi spațiu spiritual Vitoria este un personaj remarcabil. Ea oscilează între superstițîi și creștinism „în sufletul ei fiind prezentă că în cazul antagoniei voință de a-și îndeplini destinul: "Nu stăm, umblăm până găsim ce căutam. Altă rânduială n-avem ".</p>
	</article>
</section>