<section>
	<article>
		<h2 class="dipay-3 text-center">Relaţia între două personaje</h2><hr>
		<p>*Introducere de la temă şi viziunea despre lume (pe scurt — epoca, specie, particularităţi de construcţie)</p><br>
	<p>Relaţiile dintre Vitoria şi Gheorghiţă sunt evidenţiate de marile teme sadoveniene dezvoltate aici, viaţa păstorilor, natură, miturile. Acţiunea reflectă arhitectura complexă a operei, generată de parcurgerea drumului de reconstituire a faptelor care au dus la moartea bărbatului Vitoriei Lipan. Pe parcursul acestuia, Vitoria tine să îl determine pe fiul său a înţelege tragismul existenţei. Pentru Gheorghiţă, călătoria, are astfel, rolul de iniţiere.</p>
	<p>Mai mult decât atât, relaţia dintre cele două personaje este evidenţiata şi cu ajutorul statutului social, moral şi psihologic ale acestora. Vitoria este o ţărancă din Măgura Tarcaului, soţie de oier şi mama a doi copii, Minodora şi Gheorghiţă. Moral, însumează o multitudine de calităţi, fiind atât o femeie inteligenta, ambiţioasă, credincioasă, dar totodată şi una superstiţioasă şi răzbunătoare, neaflându-şi liniştea până nu reuşeşte să îi pedepsească pe cei care l-au omorât pe Nechifor. Psihologic, Vitoria afişează o persoană puternică şi o fire introvertită, ghidându-se în viaţă după proverbul: “Cine vorbeşte mult, ştie putin’. Gheorghiţă este fiu de oier înstărit şi</p>
	<p>Nu îşi schimbă statutul pe tot parcursul romanului. Moral, la început, este înfăţişat ca un copil respectuos, ascultător, timid, devenind pe parcurs mai pregătit pentru viaţă. Psihologic, întruchipează tipul tânărului în formare, a cărei personalitate se şlefuieşte prin intermediul călătoriei iniţiatice parcurse.</p>
	<p>O secvenţă semnificativă, este cea în care Vitoria şi Gheorghiţă descoperă într-o râpă osemintele lui Nechifor. Dându-şi seama că Nechifor a fost omorât undeva, între Suha şi Sabasa, aceasta, împreună cu fiul ei pornesc în căutarea lui. Cei doi dau peste Lupu, câinele lui Nechifor, care îi conduce la râpă în care se găsea trupul lui Nechifor. Vitoria se comportă ca un detective, descoperind faptul că soţul ei a fost lovit cu un baltag în ceafă şi apoi aruncat în râpă. Secvenţa demonstrează tăria de caracter a Vitoriei, dai şi perspicacitatea acesteia, deoarece încearcă să analizeze obiectiv indiciile de la locul crimei. Mai mult, coborârea în râpă permite o analogie cu coborârea în Infern, făcând trimitere la mitul lui Isis şi Osiris. De asemenea, în ceea ce-l priveşte pe Gheorghiţă, secvenţa, este deosebit de sugestivă, deoarece, lăsat să vegheze osemintele tatălui său peste noapte, este obligat practice să se maturizeze rapid.</p>
	<p>O altă secventa sugestivă, în ceea ce priveşte relaţia dintre cele două personaje, este cea a praznicului. Vitoria, că o bună credincioasă, îi organizează lui Nechifor praznicul, invitându-i şi pe cei doi criminali. În încercarea de a-i da de gol, aceasta	le adresează o multitudine de întrebări, punându-i în dificultate. Mai mult decât atât, aceasta le povesteşte cum crede că ar fi fost omorât Nechifor, moment în care Calistrat Bogza cedează nervos, devenind violet. Vitoria îi face semn lui Gheorghiţă să riposteze, iar acesta, rănit fiind, mărturiseşte crimă. Vitoria este caracterizată în mod indirect, prin comportamentul ei şi prin relaţia ei cu alte personaje ca fiind un bun cunoscător al sufletului omenesc, inteligenta şi răzbunătoare.</p>
	<p>Faţă de Gheorghiţă se comportă ca un adevărat iniţiator prin îndemnul adresat acestuia de a-şi răzbuna tatăl, Gheorghiţă devenind astfel demn de a purta baltagul. Gheorghiţă parcurge următoarele trepte ale iniţierii, copilăria fericită, drumul — pe parcursul căruia cunoaşte oameni şi lucruri noi, participarea la evenimente decisive— Botez, nuntă, înmormântare, în ordinea firească a vieţii, vegherea osemintelor tatălui său, lovirea lui Bogza şi preluarea responsabilităţilor.</p>
	<p>În opinia mea, tema textului, căutarea adevărului şi înfăptuirea dreptăţii, se reflectă în relaţia dintre Vitoria şi Gheorghiţă, ce conturează nu doar cuplul mama-fiu, ci şi iniţiator-iniţiat. În înfăptuirea dreptăţii, Gheorghiţă este “mâna dreaptă” a mamei sale, el fiind îndemnat să-l lovească pe Calistrat Bogza cu baltagul pentru a-şi răzbuna tatăl.</p>
	<p>În concluzie, personajele capătă valori simbolice prin complexitatea şi consistenţă lor. Structura psihică a ţăranului moldovean este evidenţiată de M. Sadoveanu prin surprinderea relaţiilor acestuia cu oamenii, cu lucrurile, cu tradiţiile şi obiceiurile.</p>
	</article>
</section>