<section>
	<article>
		<h2 class="dipay-3 text-center">Tema și viziunea despre lume</h2><hr>
		<p>Perioada dintre cele două războaie mondiale reprezintă un moment de referinţă în dezvoltarea prozei româneti. În această perioadă proza lui Sadoveanu, impregnată de lirism, tradiția vechilor povestitori, a cronicarilor și a cărtilor de înţelepciune, coexistă cu realismul dur obectiv al lui Rebreanu și cu romanele în care C. Petreascu și H.P Bengescu investighează profunzimile psihicului uman prin metode ale prozei eurpene moderne.
		<p>Anii interbelici se caracterizează în literatura română printr-o remarcabilă dezvoltare a romanului ce se impune că o specie literară dominantă în care sunt cuprinse medii sociale diferite și o problematică bogată și complexă. Alături de romane de inspiraţie rurală pe care îl continuă M. Sadoveanu și L. Rebreanu se dezvoltă romanul citadin a cărui necesitate era afirmată de E.Lovinescu.</p>
		<p>Baltagul a fost publicat în anul 1930 și este un roman prin complexitatea acţiunii și a conflictelor, prin consistenţa pesonajelor. Este un roman interbelic polimorf, în sensul că este tradițional-prin faptul că “preferă psihologia faptei și analiza epicului” și manifestă interes pentru aspectele sociale , istorice , mituri , datini, folclor, este un roman realist , social și obiectiv înfățișând felul în care trăiesc muntenii printr-o naraţiune la persoana a III-a, este mitic din perspectiva miturilor regăsite: mitul transhumantei , mitul lui Isis și Osiris, numele personajelor.</p>
		<p>Este un roman de dragoste deoarece Vitoria întreprinde această călătorie din dragoste pentru soțul său , un roman cu intrigă polițistă dar și un bildungsroman ce are în vedere evoluţia lui Gheorghiţă.</p>
		<p>Tema romanului este dorinţa de a afla adevărul şi de a face dreptate care se grefează pe atmosfera lumii arhaice a satului românesc, sufletul ţăranului moldovean român, păstrător al lumii vechi, al tradiţiilor și al specificului național. Că subteme pot fi evidenţiate: familia, viaa pastorală, iubirea.</p>
		<p>Titlul romanului desemnează o unealtă a civilizaţiei pastorale. De-a lungul firului epic, baltagul este amintit de mai multe ori ceea ce susține că este mai mult decât o unealtă de muncă. Este arma pusă în slujba dreptății, care se cere să rămână nefolosită în alt scop până atunci și este totodată instrumentul crimei mârșave.</p>
		<p>Acţiunea romanului este simplă, urmărind un singur fir epic: drumul Vitoriei Lipan în căutarea soțului ei, Nichifor. Structurată în șaisprezece capitole, romanul are o acţiune clară cu repere temporale și spaţiale bine determinate. Astfel acțiunea se desfășoară de toamna până primăvara, cu momente precum Sf. Andrei, Postul Mare în Măgura Tarcăului, Vatra Dornei, Borca, Cruci, Suha, Sabasa. Conflictul este sugerat încă din primele pagini ale romanului. Întârzierea soțului este sursa conflictului interior trăit de Vitoria ce se intensifică pe parcursul romanului. Conflictul exterior este relevat de confruntarea dintre Gheorghiţă și ucigașîi tatălui său.</p>
		<p>În expoziţiune, este evocată imaginea Vitoriei Lipan, îngrijorată din pricina întârzierii soţului ei. Intriga intervine când Vitoria înțelege că Nechifor nu se mai întoarce căci semnele rău-prevestitoare nu sunt puține. Desfășurarea acțiunii ilustrează drumul parcurs de munteancă alături de fiul ei Gheorghiţă, în căutarea celui dispărut. Participând conform tradiţiei la evenimentele care îi ies în cale: botezul de la Borca, nunta de la Cuci; sperând că în adunările acestea s-ar putea găsi cineva care să-i ofere indicii despre Nechifor. La fiecare popas află de bărbatul cu căciula brumărie, călare pe un cal negru ţintat. La Suha, la cârciuma lui lorgu Vasiliu îi pierde urma bărbatului căci pe acolo nu trecuse. Ajutată de nevasta hangiului, Vitoria îi găsește pe ucigași: Calistrat Bogza și llie Cuțui. Cu ajutorul câinelui Lupu găsesc osemintele lui Nechifor. Punctul culminant coincide cu scena demascării ucigașilor, la parastasul lui Nechifor. Deznodământul îl înfățișează pe Calistrat Bogza mărturisind că, împreună cu Ilie Cuţui, l-a ucis pe Nechifor pentru a-i lua oile acestuia.</p>
		<p>În ceea ce privește rânduiala și semnul, cuvinte-cheie ale interpretării romanului, se conturează de la început o viziune clară asupra lumii existente. Nimic aleatoriu nu se petrece, nici la nivel colectiv, nici la nivel individual. În ordinea prestabilită a lumii, Dumnezeu a distribuit fiecărui neam darurile cuvenite. Când la tronul dumnezeiesc s-au înfățișat cu întârziere moldovenii, călători prin munţi cu oile și cu asinii lor, nu le-au mai rămas bunuri de împărţit “Nu vă mai pot da într-adaos decât o inimă ușoară că să vă bucurați cu al vostru. Să vă pară toate bune; să vie la voi cel cu cetera; și cel cu băutura; și s-aveți muieri frumoase și iubeţe "</p>
		<p>În finalul romanului, Vitoria și Gheorghiţă se întorc în sat la viața păstorească, pentru că mereu o altă generaţie vă reface conturul existențial al părinţilor și străbunilor până la capătul vremii. Mandatul justițiar al Vitoriei s-a împlinit, ritualul integrării cosmice a celui dispărut s-a finalizat, deci viaţa poate să meargă înainte în familia Lipanilor, condusă acum de Gheorahită.</p>
		<p>Omul arhaic, desprins din mijlocul naturii autohtone, se confruntă cu lumea modernă și oscilează indecis intre a rămâne legat de izvorul care l-a creat sau a se rupe de el. Din această perspectivă raportul romanului “Baltagul” cu “Mioriţa” dezvăluie sensuri care depășesc cu mult asemănările relevate de firul narativ. Nechifor Lipan, personajul absent al romanului, este obligat de mersul noii lumi să se desprindă de natura protectoare și să coboare în Valea Dornelor, nu că cioban, ci că negustor, ceea ce diferă de motivul transhumanţei din baladă. Dacă în baladă moartea rămânea ipotetică, în roman se înfăptuieşte.</p>
		<p>Scena coborârii lui Gheorghiţă în prăpastie validează faptul că “Baltagul” este un bildungsroman. Procesul inițiatic al fiului presupune o moarte simbolică, adică coborârea în prăpastia infernală, acolo unde neiniţiatul vă fi supus unor încercări-limită, se confruntă cu imaginea îngrozitoare a rămășițelor părintelui său. Gheorghiţă iese din labirintul inițiatic un om formt și întră într-o altă etapă existenţială fiind capabil să preia conducerea familiei. Băiatul de optsprezece ani pornește pentru prima dată într-o calătorie mai lungă și decisivă pentru formarea lui. La finalul romanului, el întră într-un alt fel de existenţă, cu alte responsabilitaţi.</p>
		<p>Confruntarea dintre Vitoria și Calistrat Bogza demonstrează inteligența și energia protagonistei, dar și încheierea procesului de maturizare a lui Gheorghiță. Vitoria urmărește împlinirea legii nescrise pentru pedepsirea ucigașilor. Atunci când Bogza cere înapoi baltagul, Vitoria îl întreabă pe fiul ei dacă nu poate citi ceva pe această armă. Secena devine dramatică: Calistrat își pierde cumpătul și se repede la Gheorghiță să-i smulgă baltagul. Îl loveşte cu pumnul în frunte pe Cuţui iar Vitoria cere să dea drumul câinelui, care era legat, iar Lupu rupe lanţul. Pentru că Bogza s-a năpustit să smulgă baltagul de la Gheorghiţă și să se apere de câine, acesta se înfurie și îl lovește cu baltagul. Calistrat Bogza este culcat de oameni pe prispa casei și pentru că simţea că se stinge, mărturisește adevărul despre crima săvârșită cum a prezentat-o Vitoria.</p>
		<p>În opinia mea, tema și viziunea despre lume ilustrează, în acest roman, o societate rurală, cu obiceiuri și mentalitățile specifice locului. Altfel spus, este o monografie a lumii pastorale, care ilustrează o filozofie și un mod de viață ancestral.</p>
		În concluzie, ,Baltagul” este o scriere despre vechile norme de civilizație, despre confruntarea dintre modern și arhaic, cu triumful acestuia din urmă. Atmosfera romanului este mitică, amintind uneori de aceea din “Creanga de aur'.</p>
	</article>
</section>