<section>
	<article>
		<h2 class="dipay-3 text-center">Caracterizarea personajului Alexandru Lăpuşneanul</h2><hr>
		<p>Costache Negruzzi a fost un mare om politic şi scriitor roman din perioada paşoptistă. Alexandru Lapuşneanul este prima nuvelă istorică din literatura română, a fost publicată în primul număr al revistei Dacia literară, laşi, 1840. Reprezintă cel mai prompt răspuns la imperativul formulat de M. Kogălniceanu (mentor paşoptist) în articolul-program „introducţie” care este un program artistic de sorginte romantic, încurajând criticismul obiectiv, replierea pe elementul naţional, având ca surse folclorul, istoria sau peisajele pitoreşti autohtone. Manifestul avea ca scop scoaterea din bezna ignoranţei pe conaţionali.</p>

		<p>Alexandru Lapuşneanul este prima nuvelă istorică din literatura română, a fost” este o nuvelă romantică prin specie (nuvelă istorică este o specie preferată de romantici), prin tema (istoria este una dintre temele favorite ale romantismului), prin personajele excepţionale surprinse în situaţii excepţionale, prin antiteza dintre personaje (antiteza înger-demon care stă la baza înfăţişării relaţiei dintre Ruxanda şi Lapuşneanul , contrastul din sânul aceluiaşi personaj (Lapuşneanul este un amalgam complex de calităţi şi defecte, însă şi calităţile indubitabile sunt puse în slujba răului), culoarea epocii în descrieri cu valoare documentala, prin încercarea de evocare sub toate aspectele perioadei istorice în cauză.</p>
		
 		<p>Elementele romantice se împletesc cu cele clasice echilibrul compoziţional, construcţia simetrică, aspectul verosimil al faptelor, caracterul obiectiv al naraţiunii. Interesul romanticilor pentru specificul naţional şi culoarea locală deschide drumul observaţiei realiste pin tehnica detaliului semnificativ, caracterul pictural al unor scene, revolta mulţimii. </p>

		<p>Nuvelă este specie a genului epic în proză, cu o construcţie riguroasă, un fir narativ central ce urmăreşte evoluţia unui personaj puternic individualizat, intriga concisa, conflict concentrat. De altfel diferenţă esenţială dintre nuvelă şi povestire consta în faptul că nuvelă pune accent asupra personajului central, în vreme ce pentru povestire contează mai mult acţiunea. Ca dimensiuni, nuvelă se situează între schiţa (care se centrează tot asupra personajului, însă îl urmăreşte doar într-un moment semnificativ din viaţa lui) şi roman. Personajele sunt relativ puţine şi gravitează în jurul personajului central. Apare tendinţa de obiectivitate prin atenuarea/eliminarea prezenţei naratorului. Nuvelă se poate clasifica tematic în nuvelă istorică, fantastică sau psihologică.</p>

		<p>Tema nuvelei este lupta pentru putere în epoca medievală. Evocarea artistică a celei de-a doua domnii a lui Alexandru Lapuşneanul fixate temporal intre (1564 — 1569) evidenţiază lupta pentru impunerea autorităţii domneşti şi consecinţele deţinerii puterii de un domn crud, tiran. Tema este susţinută prin diferite secvenţe şi citate regăsite în cadrul nuvelei. Unul dintre cele mai sugestive citate este titlul primului capitol “Dacă voi nu mă vreţi, eu vă vreau!”. El este un răspuns pe care Lapuşneanul îl dă soldei de boieri care îi ceruseră să se întoarcă de unde a venit, fiindcă norodul nu îl vrea. Cu toate acestea, Lapuşneanul este hotărât să îşi reia tronul şi să se răzbune pe boierii trădători. Un alt citat sugestiv este titlul capitolului al II-lea: “Ai să dai sama doamnă!”; ce reprezintă avertismentul pe care văduva unui boier îl dă doamnei Ruxandra pentru că nu ia atitudine în fata crimelor soţului ei. </p>

		<p>Titlul este un substantiv propriu care aduce în prim plan personalitatea puternică a personajului principal, rămas în istorie mai ales pentru cea de-a doua domnie a sa, considerate a fi o perioadă extreme de sângeroasă. Numele Alexandru este foarte vechi în onomastica grecească, fiind asociat cu marii conducători-alexandru Mcedon sau Alexandru cel bun. În folclorul nostru numele Alexandru apare ca un termen de comparaţie ideal în materie de vitejie, Cei care poartă acest nume au personalităţi puternice, sunt ambiţioşi şi independenţi. Articularea numelui îl singularizează printre celelalte personaje, evidenţiindu-i totodată şi caracterul său puternic. Acţiunea este bine fixată în timp şi spaţiu, precizate şi conferă verosimilitate şi creează impresia veridicităţii naraţiunii coordonatele spaţio-temporale având astfel rolul de a orienta cititorul. Evenimentele se desfăşoară în Moldova, în a doua jumătate a secolului al-XVI-lea, prezentând întoarcerea lui Lapuşneanul la tron, în a doua să domnie. Primele trei capitol prezintă evenimente ce au loc imediat după întoarcerea lui la tron, iar ultimul rezuma evenimente întâmplate patru ani mai târziu, precum şi secventa morţii domnitorului. Naraţiunea se desfăşoară cronologic, linear, prin înlănţuirea secvenţelor narative i a episoadelor, particularitate narativă romantică.</p>

		<p>Nuvelă e împărţită în patru capitole, echilibrate. Echilibrul compoziţional este realizat prin organizarea textului narativ în patru capitole, care fixează momentele subiectului Relativ egale ca întindere, comparabile, deci, din acest punct de vedere, cu actele unei piese de teatru. Capitolele poartă câte un motto cu rol rezumativ, care constituie replic memorabile ale personajelor. Acestea trădează apetitul romanticilor pentru vorbele memorabile.</p>

		<p>Alexandru Lapuşneanul este personajul principal, numele lui constituind titlul nuvelei. Este un personaj real, cu atestare istorică, înfăţişat în timpul celei de-a doua domnii.</p>

		<p>Pe Lapuşneanul îl caracterizează cruzimea nemăsurată, provenită dintr-o ură fără margini, dusă aproape la paroxism faţă de boierimea trădătoare, lacomă de averi, spoliatoare a ţărănimii. E viclean, ipocrit, de o inteligenţă diabolică, îşi călcă jurămintele, e cinic şi de un umor macabru, atunci când îi arată doamnei Ruxandra, piramida de capete drept “un leac de frică".</p>

		<p>Nu este o simplă brută însetată de sânge, ci este un monarh absolut, ce nu tolerează opoziţia boierilor. Este lucid şi prevăzător, cere părerea altora şi îşi exprimă îndoială, este orgolios şi dârz, neabătut în hotărârea sa, nu cedează şi nu renunţa uşor "de aceea respinge categoric şi mânios pretenţia acestora de a nu intra în ţară. - ,,Dacă voi nu mă vreţi, eu va vreu pe voi, şi voi merge ori cu voia, ori fără voia voastră. Să mă-ntorc? Mai degraba-şi va întoarce Dunărea cursul îndărăpt".</p>

		<p>Lapuşneanul are o bogată experienţă, încât îşi dă seama de adevăratele intenţii ale lui Moţoc, căruia i se adresează fără menajamente: — ,,Să mă-ncred în voi?" Zise Lapuşneanul, înţelegând planul lui. ,,Pesemne gândeaţi ca eu nu ştiu zicătoarea moldovenească: Lupul părul schimba, iar năravul ba?"</p>

		<p>Totodată este un fin psiholog care sesizează cu uşurinţă caracterul şi psihologia celor din jur. Pentru el, Veveriţă este un opozant vechi şi deschis „Spancioc este patriotul tânăr şi orgolios, Stroici un copil neştiutor şi necunoscător de oameni căruia “i se pare că toate păserile ce zboară se mănâncă", iar Moţoc este învăluit în rele, "deprins a se ciocoi la toţi domnii, pe care i-a trădat pe rând."</p>

		<p>Încă de la sosirea sa "norodul pretutindene îl întâmpină cu bucurie şi nădejde, aducându-şi aminte de întâia lui domnie "căci nu-şi dă seama de adevăratul caracter al domnitorului.</p>

		<p>La el nici chiar atitudinea binevoitoare faţă de doamna Ruxandra nu este constantă ci durează doar până când aceasta îi aminteşte de crimele săvârşite:"Lapuşneanul posomorându-se, desfăcu braţele: Ruxandra căzu la picioarele lui”. </p>

		<p>Caracterizarea directă făcută de narator, este realizată prin expresii ca "aceasta deşănţata cuvântare", a-şi dezvălui uratul caracter", dorul lui cel tiranic”, vorbele tiranului "dar acestea sunt puţine, căci stilul naratorului se caracterizează prin obiectivitate. Alteori caracterizarea directă este făcută de alte personaje:"bunul meu domn”, "viteazul meu soţ (doamna Ruxandra)”, "crud şi cumplit este omul acesta (Teofan)”.</p>

		<p>Cele mai multe dintre trăsăturile de caracter sunt evidenţiate însă prin gesturi, prin mimică şi prin felul de a vorbi. Gesturile şi mimica sunt puse în evident printr-o serie de expresii, ca: "silindu-se a zâmbi", "ochii scânteiară ca un fulger", "azvârli cu mânie",  "răspunse cu sânge rece "etc... Comportamentul personajului îi reflectă şi el, indirect, însuşirile, iar acesta este relevant atât în momentele de sinceritate, de manifestare firească, cât şi de ipocrizie, de disimulare.</p>

		<p>Lapuşneanul e în stare (văzându-se popit) să profere injurii la adresa clerului „lucru înfiorător pentru acea vreme, cu atât mai groaznic cu cât el este la un pas de moarte. Ar fi fost capabil chiar să-şi ucidă soţia şi pruncul, atunci când presimte alianţa cu duşmanii lui neîmpăcaţi: "M-aţi popit voi, dar de mă voi îndrepta, pe mulţi am să popesc şi eu iar pe căţeaua asta voi s-o tai în patru bucăţi împreună cu ţancul ei, ca să nu mai asculte sfaturile boierilor şi duşmanilor mei”.</p>

		<p>Capacitatea de cruzime şi de ură a personajului este enormă şi nu se poate măsura decât cu răutatea şi intrigile boierilor, adversarilor săi. În această zbatere a sa, Alexandru Lapuşneanu devine o natură problematică.</p>

		<p>După cum se observa, Costache Negruzzi crează un personaj complex în persoana lui Alexandru Lapuşneanul.</p>
	</article>
</section>