<section>
	<article>
		<h2 class="dipay-3 text-center">Relaţia între două personaje</h2><hr>
		<p>În literatura română, numeroşi scriitori au abordat nuvela, începând cu secolul XIX. Prima operă aparţinând acestei specii literare este “Alexandru Lapuşneanul” de Costache Negruzzi, care a rămas o adevărată capodoperă apărută în anul 1840, în primul număr al revistei “Dacia literară”, nuvela “Alexandru Lapuşneanul” este romantica prin tema (prezentarea unui episod din istoria Moldovei, cea de-a doua domnie a lui Alexandru Lapuşneanul), prin construcţia personajelor, prin sursele de inspiraţie utilizate.</p>

		<p>Fiind o nuvelă, accentul este pus pe conturarea unor personaje complexe. Cele două personaje care se constituie într-un cuplu în acesta nuvelă sunt domnitorul şi soţia sa, doamna Ruxanda, personaje romantice construite pe baza antitezei. Alexandru Lapuşneanu evoluează liniar şi are un destin tragic; el s-a căsătorit cu fiica lui Petru Rareş, domniţa Ruxanda, pentru a-şi legitima pretenţiile la tron şi pentru a atrage asupra sa ceva din faimă bunicului acestuia, neuitatul Teofan cel Mare. Doamnei i se face un portret remarcabil, cu amănunte biografice şi trăsături fizice; personajul feminin dă dovadă de blândeţe, bunătate, evlavie, în antiteză cu soţul ei crud, nemilos şi tiran.</p>

		<p>Domnitorul intră în acţiune încă din incipit, când se evidenţiază şi motivaţia acestuia de a-şi recăpăta tronul, pierdut prin trădarea boierilor săi, faţă de care se arătase atât de generos în prima domnie. Personalitatea protagonistului se dezvăluie treptat căci, după ce îi exprimă voinţa de neclintit, tenacitatea, fermitatea şi energia în realizarea scopului propus, dovedeşte şi o capacitate de disimulare (evidenţiată în scenă de la mitropolie, când reuşeşte să-i convingă pe boieri că remuşcările sale sunt sincere şi să vină la curte), o inteligenţă politică desăvârşită prin spiritul vindicativ, un umor macabru când îi promite soţiei sale un “leac de frică”, concretizat ulterior într-o piramidă din capete de boieri. Lapuşneanul este şi viclean, când îi propune să se folosească de cei care îl înconjoară pentru a-i atinge obiectivul. Doamna Ruxanda are, în structura administrativă i politică a Moldovei de odinioară, statutul insignifiant pe care orice femeie îl avea în acea epocă în societate. Rugămintea ei nu devine poruncă pentru un soţ precum Alexandru Lapuşneanul, dar nici nu e respinsă brutal de acesta, promisiunea de a nu mai ucide boierii fiind făcută pentru a câştiga credibilitatea. Totuşi, aceasta e relativ respectată, căci domnitorul e dispreţuitor fata de soţia sa când o întreabă ce a determinat-o să îi “lase fusele” într-o zi oarecare şi o lasă pe aceasta să se umilească profund:"Ruxanda căzu la picioarele lui”.</p>

		<p>Respectul, încrederea şi admiraţia pe care ea i le poartă soţului reies din apelativele: "bunul meu domn!”, “viteazul meu soţ, măria-ta eşti prea puternic” şi din declaraţii “Dumnezeu ţie cât te iubesc!”, la care Lapuşneanul rămâne complet insensibil, rostind cu aroganţă “muiere nesocotită!” şi fiind pregătit să pună mâna pe jungherul de la brâu. De asemenea, în scena în care “leacul de frică” îi provoacă leşinul domniţei, domnitorul este sarcastic: "femeia tot femeie, zise Lapuşneanul zâmbind; în loc să se bucure, ea se sparie”.</p>

		<p>Scena finală a nuvelei dă posibilitatea personajului feminin să se afirme: retrasă în cetatea Hotinului să-l îngrijească pe Lapuşneanul, răpus de o boală teribilă, constată că soţul ei s-a hotărât să se călugărească dacă Dumnezeu îl va salva; dar domnitorul se dovedeşte la fel de cinic şi uită repede promisiunea făcută, ameninţând cu moartea pe cei care l-au călugărit. Doamna Ruxanda, oprită din drumul ei la ieşirea din încăperea unde se afla soţul bolnav de către cei doi boieri fugari, Spancioc şi Stroici, este îndemnată să-şi otrăvească soţul fiindu-i sugerat faptul că viaţa fiului ei, proclamat deja domn, e în primejdie. Aceasta nu are forţa necesară pentru a comite un asemenea păcat capital şi cere sprijin moral de la mitropolitul Teofan, care îi spune că aşa “crud şi cumplit” cum “e omul acesta” ar putea face mult rău şi de acum înainte. În cele din urmă, doamna Ruxanda îi duce apa otrăvită domnitorului, care moare în chinuri groaznice.</p>

		<p>Prin urmare, autorul a evidenţiat prin cele două personaje un cuplu romantic: dacă domnitorul e dur, tiranic, crud, ipocrit, impulsiv şi vindicativ, doamna Ruxanda este o fire angelică, suavă, delicată, sensibilă, sinceră, evlavioasă şi supusă. Astfel, cele două personaje sunt prezentate în antiteză şi formează un cuplu devenit celebru în literatură.</p>
	</article>
</section>