<section>
	<article>
		<h2 class="dipay-3 text-center">Temă şi viziunea despre lume </h2><hr>
		<p>Costache Negruzzi a fost un mare om politic şi scriitor roman din perioada paşoptistă. Alexandru Lapuşneanul este prima nuvelă istorică din literatura română, a fost publicată în primul număr al revistei Dacia literară, laşi, 1840. Reprezintă cel mai prompt răspuns la imperativul formulat de M. Kogălniceanu (mentor paşoptist) în articolul-program „introducţie” care este un program artistic de sorginte romantic, încurajând criticismul obiectiv, replierea pe elementul naţional, având ca surse folclorul, istoria sau peisajele pitoreşti autohtone. Manifestul avea ca scop scoaterea din bezna ignoranţei pe conaţionali.</p>

		<p>Alexandru Lapuşneanul este prima nuvelă istorică din literatura română, a fost” este o nuvelă romantică prin specie (nuvelă istorică este o specie preferată de romantici), prin tema (istoria este una dintre temele favorite ale romantismului), prin personajele excepţionale surprinse în situaţii excepţionale, prin antiteza dintre personaje (antiteza înger-demon care stă la baza înfăţişării relaţiei dintre Ruxanda şi Lapuşneanul, contrastul din sânul aceluiaşi personaj (Lapuşneanul este un amalgam complex de calităţi şi defecte, însă şi calităţile indubitabile sunt puse în slujba răului), culoarea epocii în descrieri cu valoare documentala, prin încercarea de evocare sub toate aspectele perioadei istorice în cauză.</p>

		<p>Elementele romantice se împletesc cu cele clasice echilibrul compoziţional, construcţia simetrică, aspectul verosimil al faptelor, caracterul obiectiv al naraţiunii. Interesul romanticilor pentru specificul naţional şi culoarea locală deschide drumul observaţiei realiste pin tehnica detaliului semnificativ, caracterul pictural al unor scene, revolta mulţimii.</p> 

		<p>Nuvelă este specie a genului epic în proză, cu o construcţie riguroasă, un fir narativ central ce urmăreşte evoluţia unui personaj puternic individualizat, intriga concisa, conflict concentrat. De altfel diferenţă esenţială dintre nuvelă şi povestire consta în faptul că nuvelă pune accent asupra personajului central, în vreme ce pentru povestire contează mai mult acţiunea. Ca dimensiuni, nuvelă se situează între schiţa (care se centrează tot asupra personajului, însă îl urmăreşte doar într-un moment semnificativ din viaţa lui) şi roman. Personajele sunt relativ puţine şi gravitează în jurul personajului central. Apare tendinţa de obiectivitate prin atenuarea/eliminarea prezenţei naratorului. Nuvelă se poate clasifica tematic în nuvelă istorică, fantastică sau psihologică.</p>

		<p>Tema nuvelei este lupta pentru putere în epoca medievală. Evocarea artistică a celei de-a doua domnii a lui Alexandru Lapuşneanul fixate temporal intre (1564 — 1569) evidenţiază lupta pentru impunerea autorităţii domneşti şi consecinţele deţinerii puterii de un domn crud, tiran. Tema este susţinută prin diferite secvenţe şi citate regăsite în cadrul nuvelei. Unul dintre cele mai sugestive citate este titlul primului capitol “Dacă voi nu mă vreţi, eu vă vreau!”. El este un răspuns pe care Lapuşneanul îl dă soldei de boieri care îi ceruseră să se întoarcă de unde a venit, fiindcă norodul nu îl vrea. Cu toate acestea, Lapuşneanul este hotărât să îşi reia tronul şi să se răzbune pe boierii trădători. Un alt citat sugestiv este titlul capitolului al II-lea: “Ai să dai sama doamnă!”; ce reprezintă avertismentul pe care văduva unui boier îl dă doamnei Ruxandra pentru că nu ia atitudine în fata crimelor soţului ei. </p>

		<p>Titlul este un substantiv propriu care aduce în prim plan personalitatea puternică a personajului principal, rămas în istorie mai ales pentru cea de-a doua domnie a sa, considerate a fi o perioadă extreme de sângeroasă. Numele Alexandru este foarte vechi în onomastica grecească, fiind asociat cu marii conducători-alexandru Mcedon sau Alexandru cel bun. În folclorul nostru numele Alexandru apare ca un termen de comparaţie ideal în materie de vitejie, Cei care poartă acest nume au personalităţi puternice, sunt ambiţioşi şi independenţi. Articularea numelui îl singularizează printre celelalte personaje, evidenţiindu-i totodată şi caracterul său puternic. Acţiunea este bine fixată în timp şi spaţiu, precizate şi conferă verosimilitate şi creează impresia veridicităţii naraţiunii coordonatele spaţio-temporale având astfel rolul de a orienta cititorul. Evenimentele se desfăşoară în Moldova, în a doua jumătate a secolului al-XVI-lea, prezentând întoarcerea lui Lapuşneanul la tron, în a doua să domnie. Primele trei capitol prezintă evenimente ce au loc imediat după întoarcerea lui la tron, iar ultimul rezuma evenimente întâmplate patru ani mai târziu, precum şi secventa morţii domnitorului. Naraţiunea se desfăşoară cronologic, linear, prin înlănţuirea secvenţelor narative i a episoadelor, particularitate narativă romantică.</p>

		<p>Nuvelă e împărţită în patru capitole, echilibrate. Echilibrul compoziţional este realizat prin organizarea textului narativ în patru capitole, care fixează momentele subiectului Relativ egale ca întindere, comparabile, deci, din acest punct de vedere, cu actele unei piese de teatru. Capitolele poartă câte un motto cu rol rezumativ, care constituie replic memorabile ale personajelor. Acestea trădează apetitul romanticilor pentru vorbele memorabile.</p>

		<p>Viziunea despre lume prezintă unitatea de concepţie a autorului asupra existenţei, principalele sale gânduri despre lume, despre viaţă. Ea se concretizează prin tema, specificul secventelor narative, prin construcţia personajelor. Costache Negruzzi este primul scriitor roman, care valorifica într-o creaţie literară cronicile moldoveneşti “Letopiseţul Tarii Moldovei”, de Grigore Ureche şi Miron Costin din punctul de vedere al mijloacelor artistice, pe Negruzzi îl caracterizează sobrietatea exprimării, laconismul şi precizia stilul lapidar se aseamănă cu cel cronicăresc. Înregistrarea fără înflorituri a mişcărilor, a gesturilor, a detaliilor de comportament, concizia notării reprezintă primul mare succes al prozei noastre artistice. Culoarea de epocă este realizată nu numai prin descrieri, ci şi prin limbajul cu elemente din cronici (arhaisme lexicale, dar şi construcţii sintactice arhaice). În mod surprinzător, apar şi expresii neologice prin care autorul introduce perspectiva şi planul său moral, intervenind înăuntrul ficţiunii, orientând-o pe alocuri.</p>

		<p>Nuvela îmbina armonios elemente romantice (predominante), clasice şi realiste. Această lucrare este o capodoperă, cu atât mai mult că este prima de acest fel din literatura noastră. Călinescu a evidenţiat valoarea ei estetica afirmând că dacă ar fi avut în sprijin o limbă de circulaţie universală, ar fi fost la fel de celebra ca Hamlet. A reprezentat un model pentru scrierile în proza cu caracter istoric de mai târziu, precum nuvelele Doamna Chiajna şi Mihnea-Vodă cel Rău de Odobescu. Coexistenţa trăsăturilor romantic cu cele clasice este reprezentativă pentru perioada paşoptistă.</p>
	</article>
</section>