<section>
	<article>
		<h2 class="dipay-3 text-center">Autonomii locale şi instituţii centrale în spaţial românesc <br>(Formarea statelor feudale româneşti)</h2><hr>
		<p>Pe măsura definitivării procesului de formare a poporului român şi la limbii române, numeroasele izvoare medieval oferă informaţii despre localizarea geografică şi despre originea romanilor. Printre acestea se număra lucrări, ca de exemplu: ,,Strategikon, despre administrarea imperiului ,,podoabă istoriei’’.</p>
		<p>Informaţii ne oferă şi izvoarele arheologice, cea mai veche creaţie arheologică a poporului român fiind ,, Cultura Dridei,,.</p>
		<p>Aceasta atestă existenţa obştiilor săteşti, comunităţii umane, conduse de cnezi, juzi, sfatul oamenilor buni şi bătrânii obştii. Obştea constituie elementul de unitate şi continuitate în istoria poporului român. Printr-un proces de centralizare, obştiile săteşti vor da naştere uniunilor de obşti numite de Nicolae Iorga ,,Romanii populare,, , acestea la rândul lor vor crea cnezate şi voievodate ce treptat vor duce la apariţia statelor feudale. Apariţia statelor feudale româneşti a fost favorizată de o serie de factori, printre cei interni numărându-se: creşterea demografică, procesul economic, procesul de ierarhizare socială şi existenţa formaţiunilor politice prestatale. Factorii extern ice au favorizat formarea statelor feudale româneşti au fost: decăderea puterii tătarilor, criza dinastica din Ungaria ( 1301-1308) şi disputele dintre Ungaria şi Polonia pentru controlul drumurilor comerciale. Apariţia în Europa a ultimului val de migrator ice au create un echilibru politic în zona împiedicând expansiunea Ungariei şi imperiului bizantin.</p>
		<p>Formarea Transilvaniei</p>
		<p>Între secolul al IX-lea şi al X-lea lucrarea ,, Gesta Hungarorum’’ atestă existenţa formaţiunilor conduse de Gelul, Glad şi Menumorut. Pentru secolele X, respective XI sunt atestate voievodatele conduse de Ahtum şi Gyula. Din secolul XI, maghiarii îşi intensifică acţiunile şi vor organiza comitate, primul fiind Bihorul. Vor încerca fără succes să impună principatul, izvoarele atestând existenţa unui principe Mercurius.</p>
		<p>Izvoarele amintesc însă pentru 1176 pe voievodul Leustachius Rátót. Maghiarii vor favoriza pătrunderea secuilor ce au avut rol militar precum şi a saşilor ce au avut rol economic. De-a lungul Evul Mediu, Transilvania şi-a păstrat individualitatea în cadrul Regatului Maghiar din punct de vedere economic prin ocupaţii, monedă, comerţul orientat spre Moldava şi Ţara Românească; din punct de vedere religios, ortodoxismul fiind majoritar; din punct de vedere politic fiind voievodat, administraţia fiind împărţită în comitate, scaune şi districte.</p>
		<p>Evoluţia Transilvaniei între secolele XII-XIX</p>
		<p>Principalele instituţii politice:</p>
		<p>Principatul</p>
		<p>Voievodatul</p>
		<p>VOIEVODUL – are în principal atribuţii militare, dispune de autonomie, este numit de regale maghiar cu acordul nobilimii din Transilvania. Cel mai important voievod al Transilvaniei a fost Iancu de Hunedoara.</p>
		<p>Structura religioasă</p>
		<p>Se consemnează în Transilvania sistemul celor 4 religii : calvinism catolicism, luteranism şi unitarianism.</p>
		<p>Ortodoxismul nu este recunoscut ca religie legală iar din 1366 Ludovic I de Anjou condiţionează calitatea de nobil de apartenenţa la catolicism. Acest sistem uu exclude pe romani din viaţa politică a Transilvaniei, el fiind completat cu sistemul celor 3 naţiuni privilegiate : ungurii, saşii şi secuii.</p>
		<p>Treptat în Transilvania îşi va face apariţia religia Greco-catolice prin intermediul căreia romanii au avut access la studii şi la viaţa politică. Religia a reprezentat un important element de legătură cu românii din Moldova şi Tara Românească, întrucât ortodocşii din Transilvania vor fi subordonaţi mitropoliilor celor două ţări. Legăturile cu tara românească şi moldova au fost consolidate şi de Tara românească şi Moldova au fost consolidate şi de domnitori precum Mircea cel Bătrân, Ştefan cel Mare şi Petru Rareş, ultimul fiind considerat un precursor al lui Mihai Viteazul.</p>
		<p>Între 1589-1601 Transilvania se va afla sub controlul lui Mihai Viteazul, domnitor ce va lua o serie de măsuri în favoarea romanilor şi a bisericii ortodoxe. Din punct de vedere al statutului politico- juridic, Transilvania a cunoscut ocupaţia maghiară, suzeranitatea otomană, ocupaţia austriacă iar din 19867, dualismul austro-ungar. din, suzeranitatea otomană, ocupaţia austriacă iar din 19867, dualismul austro-ungar. Din 1541 Transilvania devine principat autonom sub suzeranitate turcească. Ast înseamnă că principatul plătea tribut turcilor şi îs putea alege principele, dar trebuia să fie confirmat de sultan.</p>
		<p>Din 1699, în urma păcii de la Karlowitz, Transilvania intra sub ocupaţie austriacă iar provincial este condusă de un guvernator, numit de împăratul habsburgic. Austriecii vor menţine însă sistemul celor 3 naţiuni privilegiate şi a celor 4 religii .</p>
	</article>
</section>