<section>
	<article>
		<h2 class="dipay-3 text-center">ROMANITATEA ROMÂNILOR</h2><hr>
		<p>Fiecare popor este interesant să afle cât mai multe despre modul în care a luat naştere. În majoritatea cazurilor modul, informaţiile sunt sumare şi adesea contradictorii pentru că formarea unui popor este un proces complex şi îndelungat, ale cărui momente pot fi surprinse cu greu din documente. Cu toate acestea, fiecare naţiune doreşte să cunoască în mod cât mai precis cine au fost strămoşii săi şi cum a apărut pe scena istoriei.</p>    
		<p>Datorită acestui interes, discuţiile despre originea popoarelor, au primit în decursul vremii şi o importantă de natură politică. În fiecare scriere despre originea unui popor există, pe lângă argumente ştiinţifice, şi multă exagerare şi fantezie, datorată mai ales faptului că istoricii s-au străduit să reconstituie evenimentele la multă vreme dup ace s-au petrecut.</p>    
		<p>În Evul Mediu referinţele cu privire la romanitatea românilor sunt doar constatative, se bazează pe observaţii directe asupra limbii care era suspect de apropiată de limba latină (limba bisericii apusene) pe tradiţie şi nu în ultimul rând pe aceea ce afirmau românii – ei despre ei - . </p>    
		<p>Umanismul (secolele XIV-XVII în Europa) luând ca model anticitatea clasică Greco-Romană aruncă o privire nouă asupra trecutului şi ne oferă o imagine argumentată. Umaniştii sunt pasionaţi colecţionarii de obiecte antice. Călătorii italieni din secolul XV şi secolul XVI prezenţi în spaţial românesc, de cele mai multe ori în legătură cu interesele creştinătăţii de a se apăra în faţă presiunii otomane, afirmă că românii sunt descendenţi ai romanilor.</p>     
		<p>Primii autori români care şi-au pus problema originii poporului din care făceau parte cu fost cronicarii din secolul XVII, Grigore Ureche, Miron Costin şi Stolnicul Constantin Cantacuzino.  </p>   
		<p>În secolul XVII, în Europa, iluminismul introduce viziunea raţională asupra lumii, încrederea ca raţiunea poate impune o ordine aducătoare de beneficia pentru toţi. Iluminiştii aspiră spre o societate fără clase sociale, fărăprivilegii. În acest context, discursul istoriei devine o armă în mâna politică sunt intelectuali grupaţi în Şcoala Ardeleană (Samuil Micu, Grigore Şincai, Petru Maior)</p>     
		<p>Pretenţia unui popor de a stăpâni un teritoriu era susţinută în trecut cu argumentele dreptului istoriei, în primul rând prin afirmarea priorităţii de locuire pe teritoriul respective. Disputele din jocul dreptului istoric au înrăutăţit multă vreme relaţiile dintre popoarele vecine, cum a fost şi cazul românilor şi maghiarilor. În zilele noastre, dreptul istoriei şi-a pierdut importantă fiind înlocuit de principiul dreptului de autodeterminare naţională.Conform acestui principiu, locuitorii unei ţării pot decide liber, prin vot, viitorul politic al naţiunii din care fac parte respectând în acelaşi timp drepturile şi libertăţile minorităţilor conlocuitoare.</p>   
		<p>În concluzie, eliberarea istoriei de unele dependenţe faţă de interesele politice este menită să consolodeze caracterul ei ştiinţific şi să evite disputelecare au înveninat în trecut relaţiile politice dintre popoare şi state.</p>
	</article>
</section>