<section>
	<article>
		<h2 class="dipay-3 text-center">Caracterizarea personajului, Iona</h2><hr>
		<p> Subintitulata „tragedie în patru tablouri”, piesa „Iona" scrisă de Marin Sorescu este inclusă în trilogia dramatică „Setea muntelui de sare” alături de „Paradisul” şi „Matcă". „Iona” aparţine teatrului modern fiind o parabolă dramatică, o meditaţie asupra condiţiei omului modern. Piesă nu respecta normele clasice, tragedia ilustrând lupta individului cu destinul, dorinţa de regăsire a sinelui, definirea. Aparţinând teatrului metaforic, „Iona” este o reflecţie asupra existenţei, asupra condiţiei omului modern confruntat cu singurătatea un monolog dialogat (solilocviu) care cultivă alegoria şi metaforă.</p>

		<p>Sensul alegoric al parabolei este cuprins în mărturisirea scriitorului: „Iona sunt eu. Iona este omul în condiţia lui umană, în faţa vieţii şi a morţii”. Teatrul modern presupune eliberarea de formele dramaturgiei tradiţionale, preferinţa pentru teatrul-parabolă şi teatrul absurdului, alăturarea comicului şi tragicului, inserţia liricului, valorificarea miturilor, personajul idee, lipsa conflictului sau a temporalităţii. Tema piesei este singurătatea (,... am vrut să scriu ceva despre un om singur, nemaipomenit de singur”). Acesteia i se adăugă căutarea sinelui, revoltă în fata destinului, lipsa comunicării sociale („Ca orice om foarte singur, Iona vorbeşte tare cu sine însuşi, îşi pune întrebări şi-şi răspunde...”).</p>

		<p>Titlul trimite la mitul biblic valorificat, mitul lui Iona, proroc al Vechiului Testament trimis să propovăduiască Evanghelia în cetatea Ninive. Iona fuge pe o corabie dar Dumnezeu trimite o furtună pe mare. Iona este aruncat în valuri şi înghiţit de un chit (balena). După teri zile de pocăinţă, el este eliberat din burta peştelui. Iona parcurge avatarurile devenirii, o experienţă complexă spre luciditate în căutarea libertăţii şi a idealului în provocarea destinului. El este insul captiv într-un labirint, cercurile concentrice sunt limitele într-o luptă pentru supravieţuire. Fiinţa are o dublă identitate, vânător şi vânăt, victimă şi călău, omul în luptă cu jocul iraţional al destinului.</p>

		<p>Parabola dramatică prezintă insul ca prizonier al condiţiei sale pentru care viaţa este un şir de capcane, o succesiune de lumi închise, un spaţiu sufocant. Personajul este o metaforă, un simbol, o idee. Eroul sorescian se iniţiază în moarte nu în viaţă. Toate experienţele sale au o valoare simbolică: este pescar - ocupaţie ancestrală, vede existenţa că joc, înfrunta faţa nevăzută a lumii în burta peştelui. Drumul printre meandrele existenţei este redat prin motivul labirintului. Aşa se nasc meditaţiile despre viaţa, moarte, oameni prezentate glumeţ, aforistic sau dispreţ.</p>

		<p>Cu fiecare balenă spintecată, Iona „se naşte” din nou, ascende spre un alt nivel de cunoaştere. Încercând să meargă până la capăt, personajul încheie tragic călătoria în labirint. Tragicul nu este doar de moartea sa ci şi de faptul că trăieşte experienta fără voia să, singurul gest liber este cel al sinuciderii. Metafora luminii sfidează destinul fatal. Singurătatea, lupta unor sensuri, imposibilitatea de comunicare sunt semnele tragicului contemporan.</p>

		<p>Iona reprezintă condiţia umană, personaj singular, eponim (da titlu), simbolic. Personajul este caracterizat direct prin intervenţiile autorului şi indirect prin replici, limbaj, gesturi, acţiuni. Măreţia personajului constă în gestul său final: spintecându-şi abdomenul, aşa cum făcuse cu burţile peştilor, Iona se contopeşte cu Universul. Acesta ar putea fi sensul ultimei replici: „Răzbim noi cumva la lumină”.</p>
	</article>
</section>