<section>
	<article>
		<h2 class="dipay-3 text-center">Temă şi viziunea despre lume în opera ,,Iona”</h2><hr>
		<p>Piesa este structurata în patru tablouri care alcătuiesc o succesiune a etapelor de căutare parcurse de personaj. În primul tablou, Iona ilustrează omul obişnuit, supus, iluzionat, dornic să prindă „peştele cel mare”. El pescuieşte nepăsător, întors cu spatele şi se afla în gura deschisă a unui monstru marin care se va închide, înghiţindu-l, în finalul tabloului. Pescarul fără noroc aşteaptă peştele visat iar acvariul cu peşti care se afla lângă el este o reprezentare a lumii captive la care individul resemnat se adaptează asemeni peştişorilor care „dau veseli din coadă” deşii se afla în mediul captiv. Iona ignora pericolul şi va fi înghiţit în finalul tabloului. Imaginea marii este o metaforă a libertăţii, peştii sunt indivizii, vânat şi vânător. </p>

		<p>Tabloul al II-lea se petrece „în interiorul Peştelui I” în întuneric. Monologul lui Iona conţine idei existenţiale, meditaţii filosofice „de ce oamenii îşi pierd timpul cu lucruri ce nu le foloseşte după moarte?” Vrea să depăşească spaima singurătăţii: „fac ce vreau, vorbesc. Să vedem dacă pot să tac... nu mi-e frică”. Cuţitul găsit simbolizează libertatea iar sintagma „veşnică mistuire” ironizează legile supravieţuirii omeneşti. „Grătarul” care ar trebui să se găsească, „la intrarea în orice suflet” apare ca o formă de selecţie a lucrurilor importante, o formă de protecţie a eului. Soluţia ironic-amară găsită, sinuciderea, Iona devenind „primul pescar pescuit de el", inversarea rolurilor într-un scenariu de teatru absurd. Banca pe care lona vrea să o construiască în mijlocul marii este nevoia de siguranţă, semn de stabilitate într-o lume instabilă şi mişcătoare, dar şi de meditaţie, „de stat cu capul în mâini în mijlocul sufletului”. </p>

		<p>Tabloul al III-lea se desfăşoară în interiorul Peştelui II pe care îl înghiţise primul. Într-un discurs grav, ironic, lona meditează asupra vieţii, a condiţiei umane, a ciclicităţii viaţă-moarte. Apar doi figuranţi care cară o bârnă, povara vieţii. Moara de vânt simbolizează iluziile, zădărnicia, trecerea timpului. Optimist, lona spinteca burta peştelui dar ajunge în al treilea peste: „Altul. Mă miram eu să se termine aşa repede.</p>

		<p>Scrisoarea adresată mamei creşte dramatismul iar dorinţa „Mai naşte-mă odată!” sugerează ideea de repetabilitate. Aglomerarea de ochi din final este ameninţătoare pentru stabilitatea fiinţei. </p>

		<p>Tabloul al IV-lea îl prezintă pe lona în gura ultimului peste, aparent din nou în lumina în faţa unui orizont format din burţi de peşti uriaşi. Reapar cei doi pescari ca şi cum mereu ai întâlni aceiaşi oameni. Eroul se întoarce spre trecut, spre părinţi şi defineşte viaţa:, Cum se numea drăcia aceea frumoasă şi minunată şi nenorocită şi caraghioasă, formată din ani, pe care am trăit-o eu?”. Ieşirea din labirint nu înseamnă afară, ci spre interior. Obsesia eliberării determină spintecarea propriei burţi: „Răzbim noi cumva la lumină”. Modernitatea textului dramatic se desprinde din tema solitudinii existenţiale. Singurătatea, lipsa unor sensuri, imposibilitatea comunicării sunt elemente ale tragicului contemporan. Literatura lui Marin Sorescu este „un solilocviu demenţial, o strigare deznădăjduită către un Dumnezeu surd ca în poemele argheziene” (D.Micu). Eugen Simion constata că „opera să învăluie tragicul, sublimul, grotescul în plasa fină a ironiei”. Marin Sorescu construieşte o căutare spirituală a unui erou care caută un sens al călătoriei.</p>

		<p>„lona” aduce o înnoire radicală în teatrul românesc prin ieşirea din concretul istoric, situarea în atemporal, deschiderea spre arhetipal, rescrierea miticului biblic, trimiterile spre actualitate, trăsături ale teatrului modern.</p>
	</article>
</section>