<section>
	<article>
		<h2 class="dipay-3 text-center">Caracterizare de personajului Ştefan Tipatescu</h2><hr>
		<p>Ştefan Tipatescu este unul din personajele principale ale comediei de moravuri politice “O scrisoare pierdută”, de I.L.Caragiale, comedie ce ilustrează dorinţa de parvenire a burgheziei în timpul alegerilor de deputaţi din 1883. Acţiunea se desfăşoară în capitala unui judeţ de munte, iar conflictul dramatic se naşte între reprezentanţii opoziţiei - Caţavencu şi grupul de intelectuali independenţi şi membrii partidului de guvernământ- Tipatescu, Trahanache, Zoe, Farfuridi şi Branzovenescu.</p>

		<p>Personajul este caracterizat direct de dramaturg din tabela personajelor care îi prezintă funcţia şi statutul social, necăsătorit. Este unul dintre “stâlpii puterii” din acest judeţ, invidiat şi criticat de adversarii politici. Tipatescu este un bărbat tânăr şi prezentabil, inteligent, dar imoral, fiindcă întreţine relaţii amoroase cu Zoe, soţia prietenului de familie, Zaharia Trahanache. Orgolios nu acceptă să fie şantajat şi ameninţă cu bastonul pe Caţavencu, deşi încălca legea, poruncind poliţaiului să-l aresteze şi să-i scotocească toată casa. Devine impulsiv când Nae Caţavencu refuza a înapoia scrisoarea. Această însuşire este evidenţiată de Trahanche “bun băiat, cu carte, dar iute... nu face pentru un prefect”. Are tot timpul un aer de superioritate. Considerând că totul îi aparţine.</p>

		<p>Administrează judeţul ca pe propria moşie, propunând lui Caţavencu, în schimbul scrisorii alte funcţii importante precum: un loc în comitetul permanent, avocat al statului, primar, postul de epitrop al bisericii Sfântul Nicolae, ba chiar şi o moşie. Ştie să-l facă servil pe Pristanda, acceptându-i micile găinarii, precum cea cu steagurile, ca să fie sigur de devotamentul poliţaiului: “... dacă nu curge, pică... Lasă că ştim noi... Şi nu-mi pare rău dacă ştii să faci lucrurile cuminte: mie îmi place să mă servească funcţionarul cu tragere de inimă”.</p>

		<p>Poliţaiul sesizează cu invidie poziţia socială şi personală a şefului “moşia, moşie; funcţia, funcţie, coană Joitica, coană Joitica”. Pe plan politic, trăieşte sentimentul că a abandonat o carieră strălucită în favoarea partidului “cum să nu mă iuţesc, onorabile? D-asta veniţi la mine acasă, la mine care mi-am sacrificat cariera şi am rămas la dumneavoastră ca să vă organizez partidul”. El oscilează între dorinţă de ascensiune politică şi sentimentele faţă de Zoe, dovedind luciditate când aceasta insistă să fie ales Caţavencu şi va ceda doar când Trahanache descoperă falsul în actele lui Caţavencu. Pe Zoe o iubeşte sincer şi îi propune să-l părăsească pe Trahanache şi să fugă în lume.</p>

		<p>Personajul e caracterizat indirect prin felul de a vorbi şi de a se comporta şi din relaţia cu celelalte personaje. El stăpâneşte perfect arta disimulării: faţă de Trahanache se preface că nu ştie nimic despre scrisoare, faţă de Farfuridi şi Brânzovenescu pozează în victima, iar în faţa lui Caţavencu devine violent sau îi oferă diverse avantaje în schimbul scrisorii. Când primeşte de la Centru numele deputatului pe care “cu orice preţ” trebuie să-l aleagă, accepta compromisul. Văzându-l pe ales şi auzind povestea acestuia, exclamă indignat “Ce lume! Ce lume”.</p>

		<p>Deşi autorul îi scoate în evidenţă defectele şi viciile, acestea sunt general umane, iar personajul este privit cu o oarecare îngăduinţa neîncadrându-se în tagma politicienilor demagogi şi inculţi.</p>
	</article>
</section>