<section>
	<article>
		<h2 class="dipay-3 text-center">Caracterizare de personaj</h2><hr>
		<p>Liviu Rebreanu este considerat de către critică literară cel mai mare creator de viaţa al literaturii romane, unul dintre întemeietorii romanului romanesc modern, care se manifesta artistic în perioada interbelică.Mare parte a operei sale se încadrează curentului literar realism. Principalele sale trăsături, evidente şi în operă lui Rebreanu, sunt prezentarea veridica a realităţii, obiectivitatea, imparţialitatea, observaţia tipurilor umane caracteristice, reliefarea individului ca produs al societăţii în care trăieşte, prezentarea amănuntelor semnificative şi alcătuirea descrierilor minuţioase, stilul impersonal, sobru, precis şi concis.</p>

		<p>Stilul rebrenian se remarca prin refuzul total al subiectivismului, prin preferinţa pentru exprimarea exactă, căutând mereu "cuvântul care exprimă adevărul”. Maniera obiectivă de exprimare presupune crearea de tipuri umane cu viaţă sufletească proprie i independentă de cea a creatorului lor. În legătură cu această manieră inovatoare de a scrie, criticul literar T. Vianu afirma că Rebreanu “a dat vieţii o operă şi operei o viaţă”, afirmaţie pe deplin întemeiată. Seria romanelor rebreniene se deschide cu “lon”, publicat în anul 1920, remarcat prin obiectivitate, fiind prima scriere care se opune idilismului sămănătorist si eticismului transilvănean.</p>

		<p>Operă literară “lon” este un roman — specie a genului epic în proză, de mare întindere, Cu personaje numeroase şi acţiune complexă, desfăşurata pe mai multe planuri narative şi dezvoltând conflicte puternice. Ca tipologie este un roman realist-obiectiv prin reprezentarea veridica a societăţii romaneşti şi prin crearea unor tipuri umane aflate în strânsă legătură cu mediul din care provin, naraţiunea laa persoana a Ill-a, narator neimplicat, omniscient, omniprezent. Este şi un roman social, deoarece autorul realizează o adevărată monografie a satului ardelenesc de la începutul secolului al XX-lea, prezentând în detaliu toate aspectele vieţii rurale.</p>

		<p>Tema romanului o constituie lupta ţăranului român pentru pământ într-o societate împărţită în săraci şi bogaţi. Pe parcursul romanului se desprinde ideea că dorinţa de pământ duce la dezintegrare morală atunci când aceasta depăşite limitele normalului, transformându-se în obsesie. Viziunea despre lume se dezvoltă în jurul ideii că literatura este o creaţie e oameni şi de viaţă, da vieţii un tipar care îi surprinde dinamismul şi fluiditatea. Această proiecţie permite reprezentarea lumii cu o privire imparţială, cu o voce impasibilă, atribute ale unui narator-demiurg, omniscient, care urmăreşte existenţa umană angrenată în fluxul oarbei deveniri.</p>

		<p>Titlul operei este dat de personajul principal, eponim, sugerând caracterul comun al numelui propriu lon.Personajul lon este unul de referinţă literară română, concentrând tragica istorie a ţăranului ardelean din primele decenii ale acestui secol.Încă de la începutul romanului, la hora satului se evidenţiază dintre jucători, feciorului lui Alexandru Pop Glanetasu, lon, urmărind-o pe Ana cu 0 privire stranie, “parcă nedumerire şi un vicleşug neprefăcut”, apoi o vede pe Florica “mai frumoasă ca oricând (...) fata văduvei lui Maxim Oprea”. Deşi îi era dragă Florica, lon este conştient că “Ana avea locuri şi case şi vite multe”. Conflictul interior care marca destinul flăcăului este vizibil încă de la începutul romanului. “lute şi harnic ca mă-sa”, chipeş, voinic dar sărac, lon simte dureros prăpastia dintre el şi “bocotanii” satului ca Vasile Baciu. Când acesta-i zice “fleandură, sărăntoc, hoţ şi tâlhar”,lon se simte biciuit, nu suportă ocară şi reacţionează violent. De la început lon este sfâşiat de două forţe, glasul pământului şi glasul iubirii, căzând victimă acestor două patimi.</p>
		 
		<p>Patima pentru pământ îl măcina pentru că “pământul îi e drag ca ochii din cap”. Toată fiinţa lui este mistuită de “dorul de a avea pământ mult, cât mai mult”, deoarece “iubirea pământului l-a stăpânit de mic copil (...) de pe atunci pământul i-a fost mai drag ca o mamă. Fiind dominat de dorinţa de a fi respectat în sat, stăpânit de o dorinţă năvalnică, un temperament controlat de instincte primare, hotărât şi perseverent în atingerea scopului, dar şi viclean, lon îşi urzeşte cu meticulozitate şi pricepere planul seducerii Anei. Aşadar, setea de pământ este trăsătura dominantă a personalităţii sale, făcând din el un personaj memorabil prin aceea ca întreaga sa energie este canalizată îndeplinirii scopului de a avea pământ: “glasul pământului pătrundea năvalnic în sufletul flăcăului ca o chemare, copleşindu-l. Se simţea mic şi slab cât un vierme pe care-l calci în picioare. Altă dată, lon exclamă împătimit: “cât pământ, Doamne."</p>
		 
		<p>După ce o lăsa însărcinată pe Ana, atitudinea lui lon este rece, distantă, cinică, refuză să vorbească cu ea şi-i spune să-l trimită pe taică-său să discute. Când tratează problemă zestrei cu Vasile Baciu, lon este “semeţ şi cu nasul în vânt”, sfidător, conştient că deţine controlul absolute asupra situaţiei şi că-l poate sili să-i dea pământul la care atâta râvnise, astfel în urma comportamentului său, lon fiind caracterizat indirect. Când s-a însurat cu Ana , lon s-a însurat, de fapt, cu pământurile ei, soţia devenind o povară jalnică şi incomodă. Capitolul “Nunta” îl surprinde pe lon între cele două glasuri, devenite voci, mai întâi “ce-ar fi oare dacă aş lua pe Florica şi am fugi amândoi în lume să scap de urâţenia asta”, ca apoi, în clipa imediată următoare să gândească în sine cu dispreţ “şi să rămân tot calic pentru o muiere...</p>
		 
		<p>Trăirile lui lon în lupta pentru a intra în posesia pământurilor lui Vasile Baciu sunt cele mai diverse: de la brutalitate, violenţă, la prefăcătorie şi încântare, astfel el fiind caracterizat indirect.Odată satisfăcută patima pentru pământ, celălalt glas ce mistuie sufletul lui lon, iubirea pătimaşă pentru Florica, duce fără dubiu la destinul tragic al eroului. lon este omorât de către George, care îi prinde pe cei doi în flagrant. Astfel personajul este drastic pedepsit de autor, întrucât el se face vinovat de dezintegrare morală, răspunzător de viaţa Anei şi al copilului lor, tulburând liniştea unui cămin, a unei întregi colectivităţi.</p>	
	</article>
</section>