<section>
	<article>
		<h2 class="dipay-3 text-center">Relaţia între două personaje</h2><hr>
		<p>Liviu Rebreanu este considerat de către critica literară cel mai mare creator de viaţă al literaturii romane, unul dintre întemeietorii romanului romanesc modern, care se manifesta artistic în perioada interbelică.Mare parte a operei sale se încadrează curentului literar realism. Principalele sale trăsături, evidente şi în opera lui Rebreanu, sunt prezentarea veridică a realităţii, obiectivitatea, imparţialitatea, observaţia tipurilor umane caracteristice, reliefarea individului ca produs al societăţii în are trăieşte, prezentarea amănuntelor semnificative şi alcătuirea descrierilor minuţioase, stilul impersonal, sobru, precis şi concis.</p>

		<p>Stilul rebrenian se remarca prin refuzul total al subiectivismului, prin preferinţa pentru exprimarea exactă, căutând mereu "cuvântul care exprimă adevărul”. Maniera obiectivă de exprimare presupune crearea de tipuri umane cu viaţă sufletească proprie și independentă de cea a creatorului lor. În legătură cu această manieră inovatoare de a scrie, criticul literar T. Vianu afirmă că Rebreanu “a dat vieţii o operă şi operei o viaţă”, afirmaţie pe deplin întemeiată.Seria romanelor rebreniene se deschide cu “lon”, publicat în anul 1920, remarcat prin obiectivitate, fiind prima scriere care se opune idilismului sămănătorist şi eticismului transilvănean.</p>

		<p>Operă literară “lon” este un roman — specie a genului epic în proză, de mare întindere, Cu personaje numeroase şi acţiune complexă, desfăşurata pe mai multe planuri narative şi dezvoltând conflicte puternice. Ca tipologie este un roman realist-obiectiv prin reprezentarea veridica a societăţii romaneşti şi prin crearea unor tipuri umane aflate în strânsă legătură cu mediul din care provin, naraţiunea la persoana a III-a, narator neimplicat, omniscient, omniprezent. Este şi un roman social, deoarece autorul realizează o adevărată monografie a satului ardelenesc de la începutul secolului al XX-lea, prezentând în detaliu toate aspectele vieţii rurale.</p>

		<p>Tema romanului o constituie lupta ţăranului român pentru pământ într-o societate împărţită în săraci şi bogaţi. Pe parcursul romanului se desprinde ideea că dorinţa de pământ duce la dezintegrare morală atunci când aceasta depăşite limitele normalului, transformându-se în obsesie. Viziunea despre lume se dezvoltă în jurul ideii că literatura este o creaţie e oameni şi de viaţă, da vieţii un tipar care îi surprinde dinamismul şi fluiditatea. Această proiecţie permite reprezentarea lumii cu o privire imparţială, cu o voce impasibilă, atribute ale unui narator-demiurg, omniscient, care urmăreşte existenţa umană angrenată în fluxul oarbei deveniri.</p>

		<p>Titlul operei este dat de personajul principal, eponim, sugerând caracterul comun al numelui propriu lon.</p>

		<p>Relaţia între două personaje Statutul iniţial al celor două personaje ale căror destine se intersectează, îi aşază la polii opuși ai ierarhiei sociale: Ana este fiica celui mai bogat om din sat, iar lon este un ţăran harnic, dar sărac, însă dornic de a obţine avere. Pentru lon instinctul posesiunii este puternic, setea de pământ îl stăpâneşte, între el și pământ existând o legătură organică, sugerată în secvenţa a doua din cap. II: „Glasul pământului pătrundea năvalnic în sufletul flăcăului, ca o chemare, copleşindu-l... (:..) lubirea pământului l-a stăpânit de mic copil. Veşnic a pizmuit pe cei bogaţi şi veşnic s-a înarmat într-o hotărâre pătimaşă: trebuie să aibă mult pământ, trebuie! De pe atunci pământul i-a fost mai drag ca o mamă”. </p>

		<p>Pe de altă parte, instinctul de proprietate este în relaţie de opoziţie cu cel erotic. Ion, cel care iubeşte pământul mai mult decât pe o mamă, iubeţe în acelaşi timp, o fată fără pământ, pe Florica. De aici drama personajului care nu poate alege, ci se supune destinului, urmându-i ambiţiile. La polul opus se află Ana, personaj ce ilustrează cel mai clar tipologia victimei: îndrăgostită de lon și traumatizată de un tată prea dur, lipsită de afecţiunea maternă și de orice formă de comunicare, Ana și se oferă lui lon căutând la el afecţiunea de care a fost lipsită. Naivă și supusă
		Autorităţii masculine, ea nu poate fi decât o victimă într-o lume condusă după legi patriarhale.</p>

		<p>Statuturile psihologice ale celor doi sunt, de asemenea, antitetice: Ana e cea manipulată, iar lon manipulatorul. Din dorinţa de a-l putea forţa pe Vasile Baciu să i-o dea pe Ana, dar și pământurile, lon urmează conştient un plan de seducer a Anei, în urma căruia fata rămâne însărcinată. După ce Vasile Baciu află cine este tatăl copilului, Ana devine obiectul răzbunării celor doi bărbaţi. Paralel cu evoluţia conflictului dintre cei doi bărbaţi, Ana devine fascinată de moarte, găsind-o ca unică soluţie salvatoare. În momentul în care Savista îi spune despre relaţia dintre lon și Florica, Ana realizează că toate sacrificiile ei au fost inutile și că nici măcar copilul nu-l poate face pe lon să o iubească, în consecinţă se spânzură.</p>

		<p>În schimb, lon e consecvent în urmărirea planului său, după seducerea Anei, ignoră suferinţa acesteia din cauza bătăilor și a umilinţelor tatălui ei. În inconştienţa lui sinceră, după obţinerea pământurilor, el caută să refacă relaţiile cu Florica, femeia pe care o iubeţe.</p>

		<p>Din perspectivă morală, cele două personaje sunt victimele unor destine imanente, manipulaţi de două dorinţe diferite: lon de dorinţa de a obţine pământ, iar Ana de dorinţa de a obţine afecţiune. Ei sunt vinovaţi că încalcă legile nescrise conform cărora destinul nu poate fi schimbat, individul nu îşi poate depăşi condiţia.În ilustrarea relaţiei dintre cei doi, o scenă semnificativă este scena de la începutul romanului, când lon pleacă de la horă și o caută pe Ana, pe care o atrage la umbra unui nuc. Aici lon îi oferă ţuică, pe care Ana o refuză, amintindu-i de tatăl ei. Secvenţa următoare este realizată în stil indirect liber, în care sunt prezentate gândurile lui lon în timpul conversaţiei cu Ana:</p>

		<p>Nu-i fusese dragă Ana și nici acuma nu-i dădea bine seama dacă îi este dragă. Iubise pe Florica şi, de câte ori o vedea sau îi amintea de ea, simţea că o mai iubeţe. (...) Dar Florica era mai săracă ca dânsul, iar Ana avea locuri, şi case, și vite multe... |i asculta glasul plângător i-l cuprindea mila, în acelaşi timp se gândea la Florica."În timp ce, în sufletul personajului mai există dubii, în privinţa sentimentelor pentru Ana, receptorul textului nu are niciun dubiu că lon nu o iubeţe pe Ana, în ai cărei ochi nu se uită când îi vorbeşte, dei ea e prezentă, pe când Florica, absentă fizic de la scenă, este prezentă în mintea lui.</p>

		<p>O altă scenă semnificativă pentru relaţiile dintre cei doi este cea în care, după ce Vasile Baciu află că lon e tatăl copilului Anei, îşi trimite fata acasă la Glanetaşu. Ana ajunge la casa lui lon fără să ştie cum, dar indiferenţă cu care o primeşte lon o blochează: acesta mănâncă, tăindu-şi cu atenţie feliile de mâncare şi ştergându-şi tacticos briceagul de pantaloni, fără a se uita la femeia nenorocită din fata lui. 
		Apoi cântăreţe burta Anei cu o privire triumfătoare, după care îi spune să îşi trimită tatăl, pentru că situaţia nu poate fi rezolvată de ea. Răceala lui lon, indiferena şi detaşarea cu care el o priveşte pe Ana prefaţează destinul femeii. Ana este o victimă într-un război al bărbaţilor, o marionetă care ajunge fără să ţâre cum de la o casă la alta, pe când lon este sigur pe el, arogant și superior, iar copilul din pântecele Anei îi dă siguranţa că va reuşi.</p>
		 
		<p>În opinia mea, relaţiile dintre Ana şi lon sunt cele dintre manipulator și manipulat, însă niciunul nu reuşise să obţină ce vrea de la celălalt. Pe de-o parte, cei doi au în comun tentativa de a-i schimbă statutul: lon doreşte să-i schimbe statutul social prin obţinerea averii, pe când Ana doreşte să-i schimbe statutul psihologic, căutând iubirea. Pentru Ana, lon e un substitut al afecţiunii de care e lipsită, iar pentru lon, Ana e o cale de a se îmbogăţi rapid și sigur.
		Pe de altă parte, cei doi eşuează tocmai din cauza sincerităţii sau a incapacităţii de disimulare: Ana nu poate lua nicio atitudine faţă de lon din cauza iubirii sincere pe care i-o poartă, încât și se oferă fără a cere vreun angajament din partea lui, în vreme ce lon, brutal în sinceritatea lui, e incapabil să îi disimuleze repulsia faţă de Ana sau iubirea pentru Florica.</p>

		<p>În concluzie, cuplul lon-Ana, din romanul lon de Liviu Rebreanu, se distinge prin „maniera naturalistă în care e tratată relaţia celor doi, prin raporturile de manipulator și manipulat, dar şi prin sinceritatea instinctuală care îi împiedică pe cei doi să comunice conferindu-le celor doi statut de victime în faţa unui destin implacabil, mai ales cu cei care încearcă să îi schimbe soarta.</p>
	</article>
</section>