<section>
	<article>
		<h2 class="dipay-3 text-center">Temă şi viziunea despre lume</h2><hr>
		<p>Liviu Rebreanu este considerat de către critică literară cel mai mare creator de viaţa al literaturii romane, unul dintre întemeietorii romanului romanesc modern, care se manifesta artistic în perioada interbelică. Mare parte a operei sale se încadrează curentului literar realism. Principalele sale trăsături, evidente şi în operă lui Rebreanu, sunt prezentarea veridica a realităţii, obiectivitatea, imparţialitatea, observaţia tipurilor umane caracteristice, reliefarea individului ca produs al societăţii în care trăieşte, prezentarea amănuntelor semnificative şi alcătuirea descrierilor minuţioase, stilul impersonal, sobru, precis şi concis.</p>

		<p>Stilul rebrenian se remarca prin refuzul total al subiectivismului, prin preferinţa pentru exprimarea exactă, căutând mereu "cuvântul care exprimă adevărul”. Maniera obiectivă de exprimare presupune crearea de tipuri umane cu viaţă sufletească proprie și independentă de cea a creatorului lor. În legătură cu această manieră inovatoare de a scrie, criticul literar T. Vianu afirma că Rebreanu “a dat vieţii o operă şi operei o viaţă”, afirmaţie pe deplin întemeiată. Seria romanelor rebreniene se deschide cu “lon”, publicat în anul 1920, remarcat prin obiectivitate, fiind prima scriere care se opune idilismului sămănătorist si eticismului transilvănean.</p>

		<p>Operă literară “lon” este un roman — specie a genului epic în proză, de mare întindere, Cu personaje numeroase şi acţiune complexă, desfăşurata pe mai multe planuri narative şi dezvoltând conflicte puternice. Ca tipologie este un roman realist-obiectiv prin reprezentarea veridica a societăţii romaneşti şi prin crearea unor tipuri umane aflate în strânsă legătură cu mediul din care provin, naraţiunea la persoana a Ill-a, narator neimplicat, omniscient, omniprezent. Este şi un roman social, deoarece autorul realizează o adevărată monografie a satului ardelenesc de la începutul secolului al XX-lea, prezentând în detaliu toate aspectele vieţii rurale.</p>

		<p>Tema romanului o constituie lupta ţăranului român pentru pământ într-o societate împărţită în săraci şi bogaţi. Pe parcursul romanului se desprinde ideea că dorinţa de pământ duce la dezintegrare morală atunci când aceasta depăşite limitele normalului, transformându-se în obsesie. Viziunea despre lume se dezvoltă în jurul ideii că literatura este o creaţie e oameni şi de viaţă, da vieţii un tipar care îi surprinde dinamismul şi fluiditatea. Această proiecţie permite reprezentarea lumii cu o privire imparţială, cu o voce impasibilă, atribute ale unui narator-demiurg, omniscient, care urmăreşte existenţa umană angrenată în fluxul oarbei deveniri.</p>

		<p>Titlul operei este dat de personajul principal, eponim, sugerând caracterul comun al numelui propriu lon. Construcţia discursului narativ este simetrică, de corp sferoid şi se realizează prin descrierea drumului, din incipit şi final, care introduce cititorul în lumea ficţiunii, respectiv îl proiectează înapoi, în realitatea căreia îi aparţine. Romanul începe cu cinci imagini succesive: drumul spre satul Pripas, crucea, horă, înfruntarea verbală dintre preot și Vasile Baciu, bătaia dintre lon şi George se încheie cu reluarea aceloraşi secvenţe aşezate în ordine inversă: prăbuşirea lui lon sub loviturile lui George, altercaţia preot-Vasile Baciu, horă, troiţa cu chipul lui Hristos, drumul ce se îndepărtează de Pripas.</p>

		<p>Romanul are două pări intitulate sugestiv, "Glasul pământului” şi "Glasul iubirii” și fac referire la cele două complementare manifestate de personajul principal. Titlurile celor treisprezece capitole suni sugestive, dintre acestea putând fi amintite: “Începutul”, "lubirea”, Nunta”, "Ştreangul”, “Sfârşitul”.</p>

		<p>Finalul romanului prezintă acelaşi drum, dar care iese din universal satului spre a se pierde în şoseaua principală; se remarcă însă o altă vârstă a acestuia, care se prezintă “ca o panglică cenuşie în amurgul răcoros”. Sugestiile cromatice reliefate de incipit şi final, alb-cenuşiu, atribuite drumului, evidenţiază trecerea timpului peste un univers particular, frământat de patimi şi zguduit de conflicte puternice şi bântuit de moarte.</p>

		<p>Indicii temporali și spaţiali au rolul de a orienta cititorul în universal ficţional, dar mai ales de a crea impresia de veridicitate, acea iluzie a realului sub presiunea căreia stă tot romanul realist. Timpul, destul de vag conturat, indică plasarea acţiunii pe durata câtorva ani, la începutul secolului al XX-lea.</p>

		<p>Din punct de vedere spaţial, universal ficţiunii se plasează în imediata vecinătate a lumii reale din zona Bistriţei. Acţiunea, conturată în Pripas în cea mai mare parte, se deschide prin zone învecinate sau mai îndepărtate -— fie în realitate, fie în lumea ficţiunii: Armandia, Jidoviţa, Lechinţa, Cluj, Sibiu.</p>

		<p>Intriga romanului şi totodată începutul conflictului exterior, intre lon şi Vasile Baciu, o constituie confruntarea celor doi de după horă, acesta din urmă adresându-i tânărului cuvinte jignitoare și arătându-i dezaprobarea faţă de o eventuală legătură între el şi Ana. Lon va dori să îi răzbune ruşinea şi o va compromite pe Ana, lăsând-o însărcinată, pentru a-l determina pe tatăl fetei să accepte căsătoria. Conflictul exterior, social este dublat de cel interior, de “glasul iubirii”. După ce Ana aduce pe lume un copil, se sinucide nemaisuportând să trăiască umilită, iar lon revine la Florica, cea pe care a iubit-o dintotdeauna și este ucis de soţul acestuia, când îl surprinde noaptea venind la nevasta lui.</p>

		<p>O secvenţă sugestivă în conturarea temei şi viziunii este cea a horei, desfăşurată într-o zi de duminică la care se adună întreaga comunitate rurală. Aşezarea oamenilor indică o ierarhizare şi relaţii sociale precis delimitate. Sărăntocii, ca Alexandru Glanetau, le dau târcoale dar nu îndrăznesc să se apropie. Preotul și familia învăţătorului Herdelea "onorează” cu prezenţa petrecerea poporului dar nu participă la ea. Ritmurile someşene atrag în joc feţele şi flăcăii satului, iar vigoarea dansului trebuie să se manifeste nu numai în eliberarea de energii, ci şi în impulsul de a întemeia noi familii. Treptat, din amalgamul participanţilor la horă se detaşează o pereche de personaje antagonice: lon şi George. Autoritatea ţăranului sărac în faţa celui bogat este pusă în evidenţă de faptul că lăutarii ascultă de lon, deşi sunt plătiţi de George.</p>

		<p>Scena care evidenţiază prezenţa "factorului iraţional” este cea care explică chiar geneza romanului: sărutarea pământului. Stăpân al pământurilor, lon se simte un uriaş. În pragul primăverii, ţăranul are asupra pământului o percepţie ---, văzând în glie imaginea unei ibovnice ispititoare. Îngenuncheat în gestul mitic al sărutării pământului, lon simte un fior, dar lutul îi ţintuieşte picioarele şi îi îmbracă mâinile, prevestitor, cu nişte mânui de doliu.</p>

		<p>În secvenţa epică imediat următoare se petrece un eveniment crucial pentru destinul personajului. Când lon află că Florica se mărită cu George, se simte că şi cum cineva i-ar fi luat cea mai bună delniţă de pământ, căci pământul şi iubirea îi vorbesc cu acelaşi glas, iar aceasta precipită drumul eroului spre moarte. Moartea apare ca unică soluţie de a iei din impasul în care ajunge personajul. O violenţă de esenţă naturală răzbate din această scenă, în care sângele lui lon se întoarce în pământul care i-a fost mai drag ca o mamă, instrumental crimei fiind specific muncii pământului.</p>

		<p>În opinia mea, prezentarea verosimilă a evenimentelor oferă iluzia realităţii susţinut şi de stilul neutru impersonal.</p>

		<p>În concluzie, autor de metodă realist, Rebreanu îngăimează cititorului nu numai o lume supusă cauzalităţii, ci şi un personaj a cărei mecanică a existenţei scapă logicii, pentru că înglobează factorul iraţional.</p>
	</article>
</section>