<section>
	<article>
		<h2 class="dipay-3 text-center">Temă şi viziunea despre lume</h2><hr>
		<p>Generaţia 80' apare pe fondul unei acute crize a adevărului şi se manifesta prin refuzul compromisului, al minciunii şi al canonului cultural impus de ideologia comunistă. Scriitorii optzecişti, înzestraţi cu talent, cunoscând evoluţia literaturii în plan mondial, doresc depăşirea temelor şi formulelor artistice, impunând o schimbare fundamentală la nivelul producerii şi receptării textului literar.</p>

		<p>Mircea Nedelciu este liderul prozatorilor generaţiei 80, un valoros prozator postmodern teoretician al postmodernismului iar romanul „Zmeură de Câmpie” (1984) este unul dintre primele noastre romane postmoderne.</p>

		<p>Tema romanului o constituie raportul dintre memorie şi adevăr, neputinţa recuperării trecutului autentic. Căutarea originilor, tema fiului pierdut, ştergerea (anularea) memoriei în contextul politic, imposibilitatea, comunicării între generaţii, raportul dintre individ şi istorie, iubirea sunt pretexte utilizate de autor în scopul ilustrării trăsăturilor romanului postmodern. Titlul constituie simbolul înstrăinării, zmeură fiind o plantă de munte. Omul, despărţit de familie, trădat de memorie şi chiar de istorie, este un înstrăinat în lume.</p>

		<p>Romanul publicat în 1984 este împărţit în patru părţi şi cuprinde 24 de capitole, numerotate prin literele alfabetului de la A până la Z. Prozatorul prezintă biografiile unor tineri orfani: Radu A. Grintu, Zare Popescu şi Gelu Popescu. Aceştia au crescut fără părinţi la Casa de copii şcolari sin Sinaia. Aici, în orfelinat, Zare şi Gelu s-au făcut fraţi. După ce pleacă din casă, Zare continua să îl susţină pe Gelu. Zare este pasionat de istorie dar este respins la admitere, face armată şi lucrează ca muncitor pe şantier, la Canal. În armată, Zare îl întâlneşte pe Grintu, absolvent la Litere, aspirant la meseria de regizor. Radu Grintu, funcţionând, o vreme, pedagog la Liceul de mecanică Fină, îl întâlneşte pe Zare Popescu.</p>

		<p>Romanul ilustrează evoluţia celor trei tineri, dar şi momentele în care vieţile lor se intersectează. Subiectul cuprinde întâmplări care ţin de senzaţional, din fragmente şi coincidenţe. Subiectul operei este greu de reconstituit deoarece este creat pe baza unor fragmente, tehnica postmoderna numită „atomizarea subiectului”, adică fragmentarea, fărâmiţarea lui. De asemenea, specific romanului modern şi postmodern, acţiunea nu este redată cronologic. Naraţiunea îmbină confesiunea, jurnalul, caietul de regie a lui Radu A Grintu, scrisori, documente, citate, relatări ale martorilor sau relatarea autorului însuşi. Perspectiva narativă este multiplă, astfel, naraţiunea la persoana | şi a |l-a se împleteşte cu cea la persoana a Ill-a. Opera se adresează cititorului competent, implicat, căruia autorul i se adresează, dezvăluindu-i procedeul scrierii, metaromanul. Autorul completează, specific postmodern, observaţii ironice, auto ironice sau parodiază tehnicile romanului realist.</p>

		<p>În concluzie, „Zmeură de câmpie” este, din perspectiva artistică, un câmp de bătălie câştigător. Străbătându-l, însoţit de mişcările avântate ori derutate ale eroilor, poţi să afli, cel puţin, cine sunt fiii acelor tati sfâşiaţi de propria lor nesăbuinţă. Subiectul romanului este doar un pretext, intenţia autorului fiind pur teoretică, demonstrativa, ilustrarea trăsăturilor romanului postmodern.</p>
	</article>
</section>