<section>
	<article>
		<h2 class="dipay-3 text-center">Eu nu strivesc corola de minuni a lumii</h2><hr>
		<p> Opera lui Lucian Blaga este singular în peisajul lirici interbelice romaneşti. Nu poate fi încadrată într-un singur curent literar. În primele volume domina ecouri expresioniste. Creaţia artistică este expresia pur spiritual a realităţii interioare şi a trăirilor sufleteşti.</p>

		<p>Poet şi filosof, Lucian Blaga transpune în lirica conceptele filosofice ale cunoaşterii paradisiace, de tip logic raţional care luminează şi reduce misterul şi cunoaşterea luciferică prin care misterul este sporit. Marele Anonim instituie cenzura transcendenta care limitează cunoaşterea umană. Poezia este o artă poetică modernă publicată în mod pragmatic în fruntea volumului de debut “Poemele Luminii” 1919.</p>

		<p>Tema poezie o reprezintă atitudinea poetului în faţa marilor mistere ale universului, ilustrând concepţia Blagiană asupra cunoaşterii şi menirii poetului. Încă din titlu reluat în primul vers, poetul se defineşte pe sine prezentându-şi atitudinea asumată fata de lume: “Eu nu strivesc corola de minuni a lumii”, reţine atenţia, forma negative a verbului “nu strivesc” care prezintă atitudinea poetului în relaţia cu universal.</p>

		<p>Prima secvenţă poetică defineşte concepţia filozofică privind cunoaşterea luciferică prin verbele care resping ferm agresivitatea atitudinii de lămurire a misterelor lumii - „nu strivesc”, „nu ucid cu mintea/tainele ce te-ntâlnesc/în calea mea”. În ultimul vers al secvenţei se revelează, prin enumeraţie, simboluri esenţializate ale misterelor universului: natura înconjurătoare, viaţa, existenţa însăşi a universului („flori”); perceperea extaziantă, simţirea şi emoţia umană („ochii” sunt oglinda sufletului); comunicarea prin cuvânt şi iubirea prin sărut („buze”) şi moartea ca o componentă structurală a existenţei duale şi ciclice (voinţa-moarte), care la Blaga nu este sfârşitul dramatic, ci constituie „marea trecere” într-o lume superioară („morminte”). Marin Mincu este de părere că „enumerarea atributelor lumii este făcută nu la întâmplare, că în ordine crescândă a elementului de «mister» cuprins între ele”.</p>

		<p>Următoarea secvenţă lirică exprimă noţiunea filozofică de cunoaştere paradisiacă. „Lumina altora” este cunoaşterea de care eul liric se detaşează cu fermitate, violenţa verbului „sugrumă” fiind sugestivă pentru consecinţele pe care le-ar avea lămurirea misterelor care ar distruge „vraja nepătrunsului ascuns/în adâncimi de întuneric”. În relaţie de opoziţie cu acest tip de cunoaştere este atitudinea eului liric relevată prin conjuncţia adversativă („dar”), repetiţia pronumelui de persoana | singular („eu, eu”) i mai ales opoziţia dintre „lumină altora" şi „lumina mea”, din care reiese conceptul de cunoaştere luciferică, poetică.</p>

		<p>Pentru valenţa persuasivă (convingătoare) a acestei concepţii, eul liric apelează la comparaţia cu astrul nopţii, „luna", ale cărei raze albe plăsmuiesc difuz contururi tainice, misterioase: „şi-n tocmai cum cu razele ei albe luna/nu micşorează, ci tremurătoare/măreţe i mai tare taina nopţii”.</p>

		<p>Secvenţa poetică următoare revine la definirea cunoaşterii luciferice, proprie eului liric, care se confesează în privinţa concepţiei sale despre ocrotirea misterelor lumii: „aa îmbogăţesc i eu întunecata zare/cu largi fiori de sfânt mister/i tot ce-i neînţeles/se schimbă-n ne-nţelesuri şi mai mari/sub ochii mei”. Marca morfo sintactică a verbului la persoană I singular - „îmbogăţesc” - accentuează atitudinea sensibilă, iubitoare de perfecţiune a eului liric.</p>

		<p>Textul poetic este construit în jurul elementelor de recurenta: “misterul” şi “lumina”. La nivel morfo-sintactic se observa repetarea pronumelui “eu” care conferă caracter confesiv poeziei. La nivel stilistic se evidenţiază amplă comparative a unui element abstract, un aspect al lumii material, concrete “lumina lunii” precum şi cultivarea metaforei revelatorii. Ritmul interior reda fluxul ideilor poetului. Formă modernă este eliberată de rigorile clasice. Opera este o artă poetică modernă care transmite sentimental contopirii eului liric cu misterele universal şi defineşte creaţia ca un mijlocitor între eu şi lume.</p>
	</article>
</section>