<section>
	<article>
		<h2 class="dipay-3 text-center">Tema şi viziunea despre lume</h2><hr>
		<p>Cămil Petrescu pledează pentru o estetică a autenticităţii, în studiile teoretice şi în romanele sale. Romanul modern de tip proustian promovat de Cămil Petrescu impune un nou univers epic, o altă perspectivă narativă şi un nou tip de personaj, o conştiinţă lucidă, analitică, intelectualul, inadaptatul superior. Înnoirea romanului românesc interbelic se produce prin sincronizare cu filozofia şi ştiinţă, dar şi cu literatura universală. Romanul interbelic de analiza, cultivat Cămil Petrescu, pune accent, prin utilizarea unor tehnici ale analizei psihologice şi, adesea, a unei perspective subiective, pe descrierea a problemelor de conştiinţă sau chiar pătrunderea în zonele obscure ale inconştientului, în psihologia abisală. Ultima noapte de dragoste, întâia noapte de război este un roman modern de tip subiectiv, deoarece are drept caracteristici: unicitatea perspective narative, timpul prezent şi subiectiv, fluxul conştiinţei, memoria afectivă, naraţiunea la persoana |, luciditatea analizei, anticalofilismul, dar şi autenticitatea definite ca identificarea actului de creaţie cu realitatea vieţii, cu experienţa nepervertita, cu trăirea febrile</p>.

		<p>Viziunea despre lume a scriitorului, transferată personajului-narator Ştefan Gheorghidiu este viziunea unui spirit reflexiv cu preocupări filozofice şi literare, ceea ce dă naştere unei proze analitice de factură subiectivă. Accentul cade pe factorul psihologic, e înregistrarea şi analizarea ecoului e care îl au evenimentele exterioare în conştiinţa personajului, epicul fiind diminuat. Trăsăturile noului roman al secolului XX-lea sunt substanţialitatea şi autenticitatea. Substanţialitatea este caracteristica romanului ,,Ultima noapte de dragoste, întâia noapte de război", întrucât naraţiunea reflectă esenţa concretă a vieţii, structurându-se pe o pasiune (monografie a îndoielii), iar personajele sunt exemplificări ale unor principii, nişte conştiinţe individuale. Autenticitatea presupune reflectarea realităţii prin propria conştiinţă şi are drept marca naraţiunea la persoana I. </p>

		<p>Textul narativ este structurat în două părţi precizate în titlu, care indică temele romanului şi în acelaşi timp cele două experienţe fundamentale de cunoaştere trăite de protagonist: dragostea şi războiul. Dacă prima parte reprezintă rememorarea iubirii matrimonial eşuate dintre Ştefan Gheorghidiu şi Ela, partea a doua, construită sub forma jurnalului de campanile a lui Gheorghidiu, urmăreşte experienţa de pe front, în timpul Primului Război Mondial. Prima parte este în întregime ficţional, în timp ce de a doua valorifica jurnalul de campanile al autorului, articole şi documente din epoca, ceea ce conferă autenticitate textului.</p>

		<p>Titlul romanului indica temele acestuia şi poate fi considerat o metaforă a timpului psihologic, a modului în care timpul obiectiv şi evenimentele exterioare sunt asimilate în prezentul conştiinţei. Substantivul noapte exprima trăirea în conştiinţa şi abolirea principiului cronologic, iar cuvintele prima şi ultima sunt frontierele temporale ale unor epoci diferite fundamental prin viziune şi trăire, marcând momentele de accent ale transformării sale.</p>

		<p>Protagonistul şi, în acelaşi timp naratorul întâmplărilor din roman, Ştefan Gheorghidiu, este concentrate pe Valea Prahovei şi în aşteptarea intrării României în Primul Război Mondial. El asistă la popota ofiţerilor la o discuţie despre dragoste şi fidelitate, pornind de la un fapt divers aflat din presă: un bărbat care şi-a ucis nevasta fidelă a fost achitat de tribunal. Această discuţie declanşează memoria afectivă a protagonistului, trezindu-l amintirile legate de cei doi ani şi jumătate de căsnicie cu Ela. Episodul discuţiei de la popotă, adică un eveniment exterior, declanşează, întocmai ca la Proust, rememorarea unor întâmplări sau stări trăite într-un "timp pierdut, un timp psihologic".</p>

		<p>Ultimul capitol, intitulat Comunicat apocrif este ilustrativ pentru devenirea interioară a protagonistului. Titlul acestui capitol poate fi interpretat în dublu sens: pe de o parte, se referă la comunicatele contradictorii care sosesc de pe front, iar pe de altă parte, titlul trimite, în maniera metaforică la scrisoarea anonimă pe care o primeşte protagonistul la întoarcerea din război şi în care se dezvălui că soţia îl înşală. Ştefan nu mai verifică însă autenticitatea acestei scrisori, pentru că a oboist să se mai îndoiască şi să mai caute certitudini.</p>

		<p>Rănit şi spitalizat, Gheorghidiu revine casă, la Bucureşti, dar se simte detaşat de tot ce îl legase de Ela. O priveşte acum cu indiferenţă cu care priveşti un tablou şi hotărăşte să o părăsească: i-am scris că-i las absolut tot ce e în casă, de la obiecte de preţ la cărţi... de la lucruri personale la amintiri. Adică tot trecutul. Prin renunţare la “trecut”, adică atât la timpul trăit, cât şi la cel rememorat, Gheorghidiu se eliberează de drama erotică.</p>

		<p>Romanul este scris la persoana întâi, sub forma unei confesiuni a personajului principal, Ştefan Gheorghidiu, care trăieşte două experienţe fundamentale: iubirea şi războiul. Naraţiunea la persoana întâi, cu focalizare exclusiv internă presupune existenţa unui narator implicat. Punctul de vedere unic şi subiectiv al personajului-narator, care mediază între cititor şi celelalte personaje, îl determină pe cititor să cunoască despre ele atât cât ştie şi personajul principal. Însă situarea eului narativ în centrul povestirii conferă autenticitate, iar faptele şi personajele sunt prezentate că evenimente interioare, interpretate, analizate.</p>

		<p>Acţiunea romanului se petrece atât în mediul citadin, cât şi pe front, şi cuprinde evenimente trăite de protagonist cu aproximativ doi ani şi jumătate înainte de 1916, anul intrării României în război, cât şi din timpul desfăşurării acestuia. Însă timpul şi spaţial sunt reunite într-un prezent al trăirilor şi frământărilor interioare, în confesiunea personajului-narator.</p>

		<p>Spre deosebire de romanele tradiţionale în care conflictul se desfăşura la nivel exterior între diverse personaje, în romanul lui Cămil Petrescu, conflictul este interior şi se produce în conştiinţa personajului narator, Ştefan Gheorghidiu, care trăieşte stări şi sentimente contradictorii în ceea ce o priveşte pe soţia sa, Ela. Acest conflict interior este generat de raporturile pe care protagonistul le are cu realitatea înconjurătoare. Gheorghidiu trăieşte cu iluzia că s-a izolat de realitatea înconjurătoare, însă tocmai această realitate în care nu vrea să se implice va produce destrămarea cuplului. Implicarea Elei în lumea mondenă pe care eroul o dispreţuieşte şi faţă de care ţine să se detaşeze reprezintă principalul motiv al rupturii dintre Ştefan şi Ela. Aşadar conflictul interior trăit de protagonist se produce din cauza discrepantei dintre aspiraţiile lui Gheorghidiu şi realitatea lumii înconjurătoare.</p>

		<p>Conflictul exterior pune în evidenţă relaţia personajului cu societatea, accentuând acelaşi orgoliu al respingerii şi plasându-l în categoria inadaptaţilor social. Personajul-narator Ştefan Gherghidiu reprezintă tipul intelectualului lucid, inadaptatul superior, care trăieşte drama îndrăgostitului de absolute. Filozof, el are impresia că s-a izolat de lumea exterioară, însă în realitate, evenimentele exterioare sunt filtrate prin conştiinţa sa. Gândurile şi sentimentele celorlalte personaje nu pot fi cunoscute de cititor, decât în măsura în care se reflectă în aceasta conştient.</p>

		<p>În acest sens, Ela, personajul feminin al romanului este creaţia integrală a minţii personajului masculin, prin faptul că tot comportamentul ei este mediat de viziunea lui Ştefan. De aceea, cititorul nu se poate pronunţa asupra fidelităţii ei şi nici nu poate decide dacă e mai de grabă superficială, decât spirituală.</p>

		<p>Pe parcursul întregului roman, Ela rămâne un mister pentru cititor, deoarece ea este prezentată numai prin intermediul impresiilor lui Ştefan. Relaţia dintre cei doi soţi se bazează pe orgoliu, atât în construirea, cât şi în destrămarea ei. Ştefan începe să ţină la Ela din orgoliul de a fi iubit, gelozia lui se produce din acelaşi motiv, iar orgoliul îi împiedica pe amândoi să se împace. Ea îl iubeşte atâta timp cât e mândră de valoarea lui intelectuală în lumea lor de studenţi săraci şi se depărtează când, în noul ei cerc, soţul nu-i mai trezeşte admiraţia.</p>

		<p>Prin introspecţie şi monolog interior, tehnici ale analizei psihologice, Ştefan analizează cu luciditate, alternând sau interferând, aspect ale planului interior, din fluxul conştiinţei şi ale planului exterior. Caracterizarea directă a lui Gheorghidiu făcută de către celelalte personaje este realizată prin replici scurte, precum aceea pe care i-o adresează Ela lui Ştefan când soţul îi reproşează comportamentul ei din timpul excursiei de la Odobeşti (Eşti de o sensibilitate imposibilă). Celelalte personaje sunt caracterizate în mod direct de către personajului-narator. În acest sens, Ela este personajul feminin misterios, prin faptul că tot comportamentul ei este mediat de viziunea lui Ştefan.</p>

		<p>Ultima noapte de dragoste, întâia noapte de război este un roman modern, psihologic, având drept caracteristici: unicitatea perspective narative, timpul prezent şi subiectiv, memoria afectivă, naraţiunea la persoana I, autenticitatea trăirii şi stilul anticalofil.</p>
	</article>
</section>